export type NanoBananaReplicaItem = {
  id: string;
  rank: number;
  youmindId: number;
  title: string;
  description: string;
  summary: string;
  authorName: string;
  authorLink?: string;
  sourceLink: string;
  arenaLink: string;
  publishedAt: string;
  featured: boolean;
  grade: "A" | "B" | "C";
  needReferenceImages: boolean;
  resultsCount: number;
  imageCount: number;
  images: string[];
  promptLabel: string;
  promptText: string;
  rawPromptText: string;
  translatedPromptText?: string;
};

export const nanoBananaReplicaStats = {
  "totalLibraryItems": 3282,
  "renderedItems": 30,
  "sourceLibrary": "nano-banana-library-p001-p190",
  "lastSyncedAt": "2026-04-14T12:29:49.005Z"
} as const;

export const nanoBananaReplicaItems: NanoBananaReplicaItem[] = [
  {
    "id": "nano-banana-000001-151",
    "rank": 1,
    "youmindId": 151,
    "title": "带肖像和中英文定制的宽引言卡",
    "description": "一个用于生成宽幅引言卡的提示，卡片上有一位名人的肖像，背景为棕色，引言文字为浅金色衬线字体。布局为文字占据三分之二，人物占据三分之一。引言文字和作者可参数化以便重复使用。",
    "summary": "一个用于生成宽幅引言卡的提示，卡片上有一位名人的肖像，背景为棕色，引言文字为浅金色衬线字体。布局为文字占据三分之二，人物占据三分之一。引言文字和作者可参数化以便重复使用。",
    "authorName": "Nicolechan",
    "authorLink": "https://x.com/stark_nico99",
    "sourceLink": "https://x.com/stark_nico99/status/1991718646570426763",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=151",
    "publishedAt": "Nov 21, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 4,
    "imageCount": 4,
    "images": [
      "/nano-banana-images/000001-151/01.jpg",
      "/nano-banana-images/000001-151/02.jpg",
      "/nano-banana-images/000001-151/03.jpg",
      "/nano-banana-images/000001-151/04.jpg"
    ],
    "promptLabel": "提示词",
    "promptText": "一张宽幅引言卡片，上面印有一位名人，背景为棕色，引言文字为浅金色衬线字体：“{argument name=\"famous_quote\" default=\"Stay Hungry, Stay Foolish\"}”，下方是较小的文字：“—{argument name=\"author\" default=\"Steve Jobs\"}”。文字前面有一个大而柔和的引号。人物肖像在左侧，文字在右侧。文字占据图片的三分之二，肖像占据三分之一，肖像部分带有轻微的渐变过渡效果。",
    "rawPromptText": "一张宽幅的名人金句卡，棕色背景，衬线体浅金色“{argument name=\"金句\" default=\"保持饥饿，保持愚蠢\"}”，小字“——{argument name=\"作者\" default=\"Steve Jobs\"}”，文字前面带一个大的淡淡的引号。人物头像在左边，文字在右边，文字占画面比例 2/3，人物占 1/3，人物有一点渐变过渡的感觉。",
    "translatedPromptText": "一张宽幅引言卡片，上面印有一位名人，背景为棕色，引言文字为浅金色衬线字体：“{argument name=\"famous_quote\" default=\"Stay Hungry, Stay Foolish\"}”，下方是较小的文字：“—{argument name=\"author\" default=\"Steve Jobs\"}”。文字前面有一个大而柔和的引号。人物肖像在左侧，文字在右侧。文字占据图片的三分之二，肖像占据三分之一，肖像部分带有轻微的渐变过渡效果。"
  },
  {
    "id": "nano-banana-000002-6847",
    "rank": 2,
    "youmindId": 6847,
    "title": "高级液态玻璃 Bento 网格产品信息图，含 8 个模块",
    "description": "使用 bento grid 8 模块布局创建信息图，用户可以指定食品、药品、科技等类别中的任何产品名称，选择语言、背景样式和主网格样式。",
    "summary": "使用 bento grid 8 模块布局创建信息图，用户可以指定食品、药品、科技等类别中的任何产品名称，选择语言、背景样式和主网格样式。",
    "authorName": "Mansi Sanghani",
    "authorLink": "https://x.com/MansiSanghani1",
    "sourceLink": "https://x.com/MansiSanghani1/status/2013550795224961492",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=6847",
    "publishedAt": "Jan 20, 2026",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000002-6847/01.png",
      "/nano-banana-images/000002-6847/02.png"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "输入变量：[插入产品名称]\n语言：[插入语言]\n\n系统指令：\n创建一个包含 8 个模块（卡片 2 到 8 只显示文本标题）的优质液态玻璃 Bento 网格产品信息图。\n1) 产品分析：\n→ 识别产品的主导自然色 → “主色调”\n→ 识别类别：食品 / 药品 / 科技\n2) 调色板（源自主色调）：\n→ 产品 + 强调色：完全饱和的主色调\n→ 图标、边框：柔和的主色调（30-40% 饱和度，绝不使用黑色）\n3) 视觉风格：\n→ 主打产品：真实摄影（真实、优质）、3D 玻璃版本 [二选一]\n→ 卡片：Apple 液态玻璃（85-90% 透明），带有极细边框和微妙的阴影，营造浮动深度并反射背景颜色\n→ 背景保持在卡片后面，卡片所在区域高度模糊 [二选一]：\n  - 飘渺：产品精髓、柔和的焦散、抽象的光晕\n  - 微距：产品纹理特写、高度模糊\n  - 图案：产品柔和重复，不透明度为 10-15%\n  - 情境：相关环境，模糊 + 去饱和\n→ 添加微妙的动态效果\n→ 不对称 Bento 网格，16:9 横向\n→ 主卡片：28-30% | 信息模块：70-72%\n4) 模块内容（8 张卡片）：\nM1 — 主打：以真实照片 / 3D 玻璃 / 风格化诠释（三选一）的精美形式展示产品 + 产品名称标签\nM2 — 核心优势：4 个独特优势 + 主色调图标\nM3 — 使用方法：4 种使用方法 + 图标\nM4 — 关键指标：5 个精确数据点\n格式：[图标] [标签] [粗体值] [单位]\n食品：卡路里：[X] 千卡/100 克，碳水化合物：[X] 克（膳食纤维 [X] 克，糖 [X] 克），蛋白质：[X] 克，[关键维生素]：[X] 毫克（每日摄入量 [X]%），[关键矿物质]：[X] 毫克（每日摄入量 [X]%）\n药品：活性成分：[名称]，强度：[X] 毫克，起效时间：[X] 分钟，持续时间：[X] 小时，半衰期：[X] 小时\n科技：芯片：[型号]，电池续航：[X] 小时，重量：[X] 克，[关键规格]：[值]，连接性：[协议]\nM5 — 适用人群：4 组推荐人群，带有绿色对勾图标 | 3 组注意事项人群，带有琥珀色警告图标\nM6 — 重要提示：4 项注意事项 + 警告图标\nM7 — 快速参考：\n→ 食品：血糖指数 + 带有图标的膳食标签\n→ 药品：副作用 + 严重程度，带有图标\n→ 科技：兼容性 + 认证，带有图标\nM8 — 你知道吗：3 个事实（起源、科学、全球统计数据）+ 图标\n输出：1 张图片，16:9 横向，超优质液态玻璃信息图。",
    "rawPromptText": "Input Variable: [insert product name]\nLanguage: [insert language]\n\nSystem Instruction:\nCreate an image of premium liquid glass Bento grid product infographic with 8 modules (card 2 to 8 show text titles only).\n1) Product Analysis:\n→ Identify product's dominant natural color → \"hero color\"\n→ Identify category: FOOD / MEDICINE / TECH\n2) Color Palette (derived from hero):\n→ Product + accents: full saturation hero color\n→ Icons, borders: muted hero (30-40% saturation, never black)\n3) Visual Style:\n→ Hero product: real photography (authentic, premium), 3D Glass version [choose one]\n→ Cards: Apple liquid glass (85-90% transparent) with Whisper-thin borders and Subtle drop shadow for floating depth and reflecting the background color\n→ Background stays behind cards and high blur where cards are [choose one]:\n  - Ethereal: product essence, light caustics, abstract glow\n  - Macro: product texture close-up, heavily blurred\n  - Pattern: product repeated softly at 10-15% opacity\n  - Context: relevant environment, blurred + desaturated\n→ Add subtle motion effect\n→ Asymmetric Bento grid, 16:9 landscape\n→ Hero card: 28-30% | Info modules: 70-72%\n4) Module Content (8 Cards):\nM1 — Hero: Product displayed as real photo / 3D glass / stylized interpretation (choose one)in beautiful form + product name label\nM2 — Core Benefits: 4 unique benefits + hero-color icons\nM3 — How to Use: 4 usage methods + icons\nM4 — Key Metrics: 5 EXACT data points\nFormat: [icon] [Label] [Bold Value] [Unit]\nFOOD: Calories: [X] kcal/100g, Carbs: [X]g (fiber [X]g, sugar [X]g), Protein: [X]g, [Key Vitamin]: [X]mg ([X]% DV), [Key Mineral]: [X]mg ([X]% DV)\nMEDICINE:Active: [name], Strength: [X] mg, Onset: [X] min, Duration: [X] hrs, Half-life: [X] hrs \nTECH:Chip: [model], Battery: [X] hrs, Weight: [X]g,[Key spec]: [value], Connectivity: [protocols]\nM5 — Who It's For: 4 recommended groups with green checkmark icons | 3 caution groups with amber warning icons\nM6 — Important Notes: 4 precautions + warning icons\nM7 — Quick Reference:\n→ FOOD: Glycemic Index + dietary tags with icons\n→ MEDICINE: Side effects + severity with icons\n→ TECH: Compatibility + certifications with icons\nM8 — Did You Know: 3 facts (origin, science, global stat) + icons\nOutput: 1 image, 16:9 landscape, ultra-premium liquid glass infographic.",
    "translatedPromptText": "输入变量：[插入产品名称]\n语言：[插入语言]\n\n系统指令：\n创建一个包含 8 个模块（卡片 2 到 8 只显示文本标题）的优质液态玻璃 Bento 网格产品信息图。\n1) 产品分析：\n→ 识别产品的主导自然色 → “主色调”\n→ 识别类别：食品 / 药品 / 科技\n2) 调色板（源自主色调）：\n→ 产品 + 强调色：完全饱和的主色调\n→ 图标、边框：柔和的主色调（30-40% 饱和度，绝不使用黑色）\n3) 视觉风格：\n→ 主打产品：真实摄影（真实、优质）、3D 玻璃版本 [二选一]\n→ 卡片：Apple 液态玻璃（85-90% 透明），带有极细边框和微妙的阴影，营造浮动深度并反射背景颜色\n→ 背景保持在卡片后面，卡片所在区域高度模糊 [二选一]：\n  - 飘渺：产品精髓、柔和的焦散、抽象的光晕\n  - 微距：产品纹理特写、高度模糊\n  - 图案：产品柔和重复，不透明度为 10-15%\n  - 情境：相关环境，模糊 + 去饱和\n→ 添加微妙的动态效果\n→ 不对称 Bento 网格，16:9 横向\n→ 主卡片：28-30% | 信息模块：70-72%\n4) 模块内容（8 张卡片）：\nM1 — 主打：以真实照片 / 3D 玻璃 / 风格化诠释（三选一）的精美形式展示产品 + 产品名称标签\nM2 — 核心优势：4 个独特优势 + 主色调图标\nM3 — 使用方法：4 种使用方法 + 图标\nM4 — 关键指标：5 个精确数据点\n格式：[图标] [标签] [粗体值] [单位]\n食品：卡路里：[X] 千卡/100 克，碳水化合物：[X] 克（膳食纤维 [X] 克，糖 [X] 克），蛋白质：[X] 克，[关键维生素]：[X] 毫克（每日摄入量 [X]%），[关键矿物质]：[X] 毫克（每日摄入量 [X]%）\n药品：活性成分：[名称]，强度：[X] 毫克，起效时间：[X] 分钟，持续时间：[X] 小时，半衰期：[X] 小时\n科技：芯片：[型号]，电池续航：[X] 小时，重量：[X] 克，[关键规格]：[值]，连接性：[协议]\nM5 — 适用人群：4 组推荐人群，带有绿色对勾图标 | 3 组注意事项人群，带有琥珀色警告图标\nM6 — 重要提示：4 项注意事项 + 警告图标\nM7 — 快速参考：\n→ 食品：血糖指数 + 带有图标的膳食标签\n→ 药品：副作用 + 严重程度，带有图标\n→ 科技：兼容性 + 认证，带有图标\nM8 — 你知道吗：3 个事实（起源、科学、全球统计数据）+ 图标\n输出：1 张图片，16:9 横向，超优质液态玻璃信息图。"
  },
  {
    "id": "nano-banana-000003-498",
    "rank": 3,
    "youmindId": 498,
    "title": "手绘风格标题图片提示（来自照片）",
    "description": "手绘风格的头部图片，描绘一个人正在介绍 Nano Banana Pro。",
    "summary": "手绘风格的头部图片，描绘一个人正在介绍 Nano Banana Pro。",
    "authorName": "セミナー講師専門AIコンシェルジュ｜工藤 晶",
    "authorLink": "https://x.com/akirakudo_ai",
    "sourceLink": "https://x.com/akirakudo_ai/status/1992096860765561190",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=498",
    "publishedAt": "Nov 22, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000003-498/01.jpg",
      "/nano-banana-images/000003-498/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "完全重塑上传的人物。\n将其作为一篇笔记文章的标题图片，该人物在文章中介绍“Nano Banana Pro”。\n长宽比：横向 16:9。\n风格和颜色：简洁、手绘风格、斜体，带有蓝绿色渐变。\n标题文字：“深入解读 Google 全新 AI ‘Nano Banana Pro’”。",
    "rawPromptText": "アップロードした人物を完全再現\nその人物が「Nano Banana Pro」を紹介する note記事の見出し画像\n16：9の横長サイズ\nスタイル、カラー：シンプル、手描き風、斜体、青と緑のグラデーション\nタイトル：Google の新AI「Nano\nBanana Pro」徹底解説",
    "translatedPromptText": "完全重塑上传的人物。\n将其作为一篇笔记文章的标题图片，该人物在文章中介绍“Nano Banana Pro”。\n长宽比：横向 16:9。\n风格和颜色：简洁、手绘风格、斜体，带有蓝绿色渐变。\n标题文字：“深入解读 Google 全新 AI ‘Nano Banana Pro’”。"
  },
  {
    "id": "nano-banana-000004-380",
    "rank": 4,
    "youmindId": 380,
    "title": "德国水彩地图，附带各州名称",
    "description": "一个德语提示，用于生成一张水彩风格的德国地图，其中所有联邦州都用圆珠笔标注，适用于教育或信息图表风格的地图。",
    "summary": "一个德语提示，用于生成一张水彩风格的德国地图，其中所有联邦州都用圆珠笔标注，适用于教育或信息图表风格的地图。",
    "authorName": "Florian Gallwitz",
    "authorLink": "https://x.com/FlorianGallwitz",
    "sourceLink": "https://x.com/FlorianGallwitz/status/1991796624646091091",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=380",
    "publishedAt": "Nov 21, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000004-380/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "生成一张水彩风格的德国地图，并在地图上用圆珠笔标出所有联邦州。",
    "rawPromptText": "Erzeuge eine Karte von Deutschland im Wasserfarben-Stil, auf der alle Bundesl�nder mit Kugelschreiber benannt sind.",
    "translatedPromptText": "生成一张水彩风格的德国地图，并在地图上用圆珠笔标出所有联邦州。"
  },
  {
    "id": "nano-banana-000005-4031",
    "rank": 5,
    "youmindId": 4031,
    "title": "元旦特辑：2026 祝福四格拼图",
    "description": "这是一个为 Nano Banana Pro 设计的详细多面板提示，用于创建一个 2x2 网格照片拼贴画。画面中，一位女性角色身着四套不同的服装，在四个不同的场景中拼凑一个拼图，拼图的中心显示“2026 新年快乐”。该提示详细说明了面部特征的精确保留、服装细节、背景元素以及时尚杂志风格的照片参数。",
    "summary": "这是一个为 Nano Banana Pro 设计的详细多面板提示，用于创建一个 2x2 网格照片拼贴画。画面中，一位女性角色身着四套不同的服装，在四个不同的场景中拼凑一个拼图，拼图的中心显示“2026 新年快乐”。该提示详细说明了面部特征的精确保留、服装细节、背景元素以及时尚杂志风格的照片参数。",
    "authorName": "松果先森",
    "authorLink": "https://x.com/songguoxiansen",
    "sourceLink": "https://x.com/songguoxiansen/status/2005822648027091031",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=4031",
    "publishedAt": "Dec 30, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000005-4031/01.jpg"
    ],
    "promptLabel": "提示词",
    "promptText": "[关键：保持精确的面部特征，保留原始面部结构，图像中的人物必须与上传的参考图像完全一致] 高端照相馆 2x2 网格照片。左上角面板（海军蓝背景）：人物身穿海军蓝制服式连衣裙，饰有金色纽扣，复古卷发，戴蓝色贝雷帽和珍珠耳环。她双手举起一块巨大的拼图（左上角拼图，上面有数字“20”），将其移向画面中心。她的目光聚焦在中央拼图区域，表情严肃，略带微笑。背景是海军条纹、一个锚和文字“扬帆新年”。右上角面板（樱花粉背景）：同一位女士身穿粉色蕾丝连衣裙，戴珍珠项链，公主发型，戴粉色玫瑰发夹和水晶耳环。她双手举起右上角拼图（上面有数字“26”），将其移向中心，与左上角拼图连接。她的目光看向拼图接缝处，表情专注而期待，身体前倾。背景是粉色樱花、文字“美丽邂逅”、蝴蝶和花瓣。左下角面板（薄荷绿背景）：同一位女士身穿薄荷绿棉麻连衣裙，艺术风格，自然长发，戴绿色发带和木质耳环。她双手举起左下角拼图（上面有文字“元旦”），将其向上移动，与左上角拼图连接。她的目光看向拼图，表情严肃，嘴唇微抿。背景是绿色植物、文字“希望生长”、新芽和树叶。右下角面板（柠檬黄背景）：同一位女士身穿带有向日葵图案的黄色连衣裙，扎着黄色蝴蝶结的辫子。她将最后一块右下角拼图（上面有文字“快乐”）推入，完成拼图。四块拼图完美地在画面中心形成了完整的图案“2026 元旦快乐”。她向后仰头，看着完成的拼图，脸上洋溢着成功喜悦的笑容。画面中心爆发出金色光芒和五彩纸屑。背景是黄色太阳、文字“圆满成功”、笑脸和向日葵。拼图从四个角落汇聚到中心，形成一幅完整的画面。清晰的妆容，明亮的环形灯，85mm 镜头，f/1.8 光圈，四格构图，拼图互动，时尚杂志风格。",
    "rawPromptText": "[关键:保持精确的面部特征,保留原始脸部结构,图中角色与上传参考图完全一致] 高级摄影棚2x2宫格写真。左上格(海军蓝背景):人物穿海军蓝色制服风连衣裙,金色纽扣装饰,复古卷发配蓝色贝雷帽和珍珠耳环,她双手托举一块巨大的拼图块(左上角块,上面有\"20\"数字),向画面中心方向移动,眼神专注地看向中心拼图区域,表情认真,嘴角微笑,背景有海军条纹、船锚、\"启航新年\"字样。右上格(樱花粉背景):同一女性穿粉色蕾丝连衣裙,珍珠项链,公主头配粉色玫瑰花发夹和水晶耳环,她双手托举右上角拼图块(上面有\"26\"数字)向中心移动与左上格拼接,眼神看向拼图接缝处,表情专注期待,身体前倾,背景有粉色樱花、\"美好相遇\"字样、蝴蝶、花瓣。左下格(薄荷绿背景):同一女性穿薄荷绿色棉麻连衣裙,文艺风格,自然长发配绿色发带和木质耳环,她双手托举左下角拼图块(上面有\"元旦\"字样)向上移动与左上格对接,眼神看向拼图,表情认真,嘴巴微微抿起,背景有绿色植物、\"希望生长\"字样、新芽、叶子。右下格(柠檬黄背景):同一女性穿黄色连衣裙,向日葵图案,双马尾配黄色蝴蝶结,她双手托举最后一块右下角拼图(上面有\"快乐\"字样)完成拼图,四块拼图在画面中心完美拼成\"2026元旦快乐\"完整图案,她头后仰,眼睛看向完成的拼图,脸上洋溢着成功喜悦的笑容,画面中心爆出金色光芒和彩纸,背景有黄色太阳、\"圆满成功\"字样、笑脸、向日葵。四格之间拼图从四角汇聚到中心形成完整画面,清透妆容,明亮环形光,85mm镜头,f/1.8光圈,拼图互动四联构图,时尚杂志风格。",
    "translatedPromptText": "[关键：保持精确的面部特征，保留原始面部结构，图像中的人物必须与上传的参考图像完全一致] 高端照相馆 2x2 网格照片。左上角面板（海军蓝背景）：人物身穿海军蓝制服式连衣裙，饰有金色纽扣，复古卷发，戴蓝色贝雷帽和珍珠耳环。她双手举起一块巨大的拼图（左上角拼图，上面有数字“20”），将其移向画面中心。她的目光聚焦在中央拼图区域，表情严肃，略带微笑。背景是海军条纹、一个锚和文字“扬帆新年”。右上角面板（樱花粉背景）：同一位女士身穿粉色蕾丝连衣裙，戴珍珠项链，公主发型，戴粉色玫瑰发夹和水晶耳环。她双手举起右上角拼图（上面有数字“26”），将其移向中心，与左上角拼图连接。她的目光看向拼图接缝处，表情专注而期待，身体前倾。背景是粉色樱花、文字“美丽邂逅”、蝴蝶和花瓣。左下角面板（薄荷绿背景）：同一位女士身穿薄荷绿棉麻连衣裙，艺术风格，自然长发，戴绿色发带和木质耳环。她双手举起左下角拼图（上面有文字“元旦”），将其向上移动，与左上角拼图连接。她的目光看向拼图，表情严肃，嘴唇微抿。背景是绿色植物、文字“希望生长”、新芽和树叶。右下角面板（柠檬黄背景）：同一位女士身穿带有向日葵图案的黄色连衣裙，扎着黄色蝴蝶结的辫子。她将最后一块右下角拼图（上面有文字“快乐”）推入，完成拼图。四块拼图完美地在画面中心形成了完整的图案“2026 元旦快乐”。她向后仰头，看着完成的拼图，脸上洋溢着成功喜悦的笑容。画面中心爆发出金色光芒和五彩纸屑。背景是黄色太阳、文字“圆满成功”、笑脸和向日葵。拼图从四个角落汇聚到中心，形成一幅完整的画面。清晰的妆容，明亮的环形灯，85mm 镜头，f/1.8 光圈，四格构图，拼图互动，时尚杂志风格。"
  },
  {
    "id": "nano-banana-000006-3438",
    "rank": 6,
    "youmindId": 3438,
    "title": "一项发明的复古专利文件",
    "description": "一个旨在生成 19 世纪末美国复古专利文件图像的提示。它指定了精确的技术图纸、手写注释、陈旧的纸张纹理、锈斑、浮雕印章和蜡封等细节，非常适合历史或档案美学。",
    "summary": "一个旨在生成 19 世纪末美国复古专利文件图像的提示。它指定了精确的技术图纸、手写注释、陈旧的纸张纹理、锈斑、浮雕印章和蜡封等细节，非常适合历史或档案美学。",
    "authorName": "Alexandra Aisling",
    "authorLink": "https://x.com/AllaAisling",
    "sourceLink": "https://x.com/AllaAisling/status/2004212035333365763",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=3438",
    "publishedAt": "Dec 25, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 4,
    "imageCount": 4,
    "images": [
      "/nano-banana-images/000006-3438/01.jpg",
      "/nano-banana-images/000006-3438/02.jpg",
      "/nano-banana-images/000006-3438/03.jpg",
      "/nano-banana-images/000006-3438/04.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一份关于 {argument name=\"invention\" default=\"INVENTION\"} 的复古专利文件，其风格仿照 19 世纪末美国专利局的备案文件。页面上印有精确的技术图纸，并带有编号标注（图 1、图 2、图 3），展示了正面、侧面和分解视图。钢笔墨水手写批注描述了机械装置。纸张呈陈旧的象牙色，带有锈斑和柔和的折痕。角落处有一个官方浮雕印章和红色蜡封。底部有发明者的手写签名和日期。整个图像给人一种从档案中找回的权威、历史且略带神秘感的文件之感。",
    "rawPromptText": "A vintage patent document for {argument name=\"invention\" default=\"INVENTION\"}, styled after late 1800s United States Patent Office filings. The page features precise technical drawings with numbered callouts (Fig. 1, Fig. 2, Fig. 3) showing front, side, and exploded views. Handwritten annotations in fountain-pen ink describe mechanisms. The paper is aged ivory with foxing stains and soft fold creases. An official embossed seal and red wax stamp appear in the corner. A hand-signed inventor's name and date appear at the bottom. The entire image feels like a recovered archival document—authoritative, historic, and slightly mysterious.",
    "translatedPromptText": "一份关于 {argument name=\"invention\" default=\"INVENTION\"} 的复古专利文件，其风格仿照 19 世纪末美国专利局的备案文件。页面上印有精确的技术图纸，并带有编号标注（图 1、图 2、图 3），展示了正面、侧面和分解视图。钢笔墨水手写批注描述了机械装置。纸张呈陈旧的象牙色，带有锈斑和柔和的折痕。角落处有一个官方浮雕印章和红色蜡封。底部有发明者的手写签名和日期。整个图像给人一种从档案中找回的权威、历史且略带神秘感的文件之感。"
  },
  {
    "id": "nano-banana-000007-509",
    "rank": 7,
    "youmindId": 509,
    "title": "黑板风格的 AI 新闻摘要",
    "description": "一个日文提示，用于将 AI 新闻内容转化为手绘的、教师风格的黑板图，并附带解释。",
    "summary": "一个日文提示，用于将 AI 新闻内容转化为手绘的、教师风格的黑板图，并附带解释。",
    "authorName": "ひでもん | AI開発@ニュース発信",
    "authorLink": "https://x.com/okknews",
    "sourceLink": "https://x.com/okknews/status/1992173611520868372",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=509",
    "publishedAt": "Nov 22, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000007-509/01.jpg",
      "/nano-banana-images/000007-509/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "使用以下内容，以黑板风格、手写体的外观总结新闻，并像老师写的一样，用图表和易于理解的表达方式进行分解。\n—-\nGrok 的搜索结果",
    "rawPromptText": "以下を内容で黒板風の手書きみたいな感じでニュースをまとめて、先生が書いたみたいに図解や分かりやすい表現に噛み砕いてよろしく。\n—-\nGrokの検索結果",
    "translatedPromptText": "使用以下内容，以黑板风格、手写体的外观总结新闻，并像老师写的一样，用图表和易于理解的表达方式进行分解。\n—-\nGrok 的搜索结果"
  },
  {
    "id": "nano-banana-000008-553",
    "rank": 8,
    "youmindId": 553,
    "title": "详细的镜子自拍御宅族房间场景",
    "description": "一个非常详细的 Nano Banana 提示，描述了一位女性在蓝色调御宅族电脑角拍摄的镜面自拍，包含角色、环境、灯光、相机和负面提示的完整规格。",
    "summary": "一个非常详细的 Nano Banana 提示，描述了一位女性在蓝色调御宅族电脑角拍摄的镜面自拍，包含角色、环境、灯光、相机和负面提示的完整规格。",
    "authorName": "宝玉",
    "authorLink": "https://x.com/dotey",
    "sourceLink": "https://x.com/dotey/status/1976485558319722711",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=553",
    "publishedAt": "Oct 10, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 4,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000008-553/01.jpg"
    ],
    "promptLabel": "提示词",
    "promptText": "### 场景\n宅男风格电脑角里的镜面自拍，蓝色调。\n\n### 主体\n* 性别表达：女性\n* 年龄：25 岁左右\n* 种族：东亚裔\n* 身材：苗条，腰部线条分明；身体比例自然\n* 肤色：浅中性色调\n* 发型：\n    * 长度：及腰长发\n    * 样式：直发，发梢微卷\n    * 颜色：中棕色\n* 姿势：\n    * 站姿：略呈对立式平衡站姿\n    * 右手：手持智能手机置于脸前（身份隐藏）\n    * 左臂：自然下垂于身体两侧\n    * 躯干：身体略微后倾；腰部和腹部露出\n* 服装：\n    * 上衣：浅蓝色短款针织开衫，上面两颗纽扣扣上；隐约可见一件蓝色法式文胸\n    * 下装：牛仔超短裤，臀部两侧各有一个蓝色缎带蝴蝶结\n    * 袜子：蓝白条纹过膝袜\n    * 配饰：一个蓝色可爱吉祥物手机壳\n\n### 环境\n* 描述：通过壁挂镜看到的卧室电脑角\n* 家具：\n    * 白色书桌\n    * 单显示器显示柔和的蓝色壁纸（无可读文本）\n    * 机械键盘，白色键帽，置于蓝色桌垫上\n    * 鼠标置于一个小型蓝色鼠标垫上\n    * 右侧的电脑主机，带有蓝色机箱灯\n    * 电脑主机上或附近有三个动漫手办\n    * 墙上有一张宝塔海报\n    * 猫形台灯，带蓝色点缀\n    * 一杯透明玻璃水\n    * 窗边有一株高大的绿色阔叶植物（画面左侧）\n* 颜色替换：将所有原为粉色的元素（衣服和房间装饰）替换为蓝色调（从婴儿蓝到天蓝色/长春花蓝）。\n\n### 灯光\n* 光源：来自相机左侧大窗户的日光，透过薄纱窗帘\n* 光线质量：柔和、漫射光\n* 白平衡 (K)：5200\n\n### 相机\n* 模式：智能手机后置摄像头通过镜子拍摄（无人像/散景模式）\n* 等效焦距 (mm)：26\n* 距离 (m)：\n    * 主体到镜子：0.6\n    * 相机到镜子：0.5\n* 曝光：\n    * 光圈 (f)：1.8\n    * ISO：100\n    * 快门速度 (s)：0.01\n    * 曝光补偿 (EV)：-0.3\n* 对焦：对焦于镜面图像中的躯干和短裤\n* 景深：智能手机自然的深景深；背景清晰可见，无人工模糊\n* 构图：\n    * 宽高比：1:1\n    * 裁剪：从头顶到大腿中部；画面中包含书桌、显示器、电脑主机和植物\n    * 角度：从镜子的视角看，略微高角度\n    * 构图说明：主体居中；为避免广角边缘畸变，让她站得稍远一些，之后再裁剪成正方形。\n\n### 负面提示\n* 任何地方出现粉色/洋红色\n* 美颜滤镜/过度平滑的皮肤；无毛孔皮肤外观\n* 夸张或扭曲的解剖结构\n* 不雅内容、透视织物、走光\n* 标志、品牌名称或可读的用户界面文本\n* 虚假的人像模式模糊、CGI/插画感",
    "rawPromptText": "### **场景**\n镜子自拍，御宅族电脑角落，蓝色调\n\n---\n\n### **主体**\n* **性别表现**: 女性\n* **年龄段**: 25岁左右\n* **种族**: 东亚\n* **身材**: 苗条，腰线分明；身材比例自然\n* **肤色**: 浅中性色调\n* **发型**:\n    * **长度**: 及腰长发\n    * **样式**: 直发，发尾微卷\n    * **颜色**: 中等棕色\n* **姿势**:\n    * **站姿**: 站立，轻微的对立式平衡站姿（contrapposto）\n    * **右手**: 手持手机挡住脸（身份被遮挡）\n    * **左臂**: 在躯干旁自然下垂\n    * **躯干**: 身体轻微后仰；露出腰腹\n* **着装**:\n    * **上衣**: 浅蓝色短款针织开衫，扣上前两颗纽扣；隐约可见蓝色法式内衣\n    * **下装**: 牛仔超短裤，两侧臀部各有一个蓝色缎带蝴蝶结\n    * **袜子**: 蓝白横条纹过膝长袜\n    * **配饰**: 蓝色可爱吉祥物手机壳\n\n---\n\n### **环境**\n* **描述**: 从挂墙镜中看到的卧室电脑角落\n* **陈设**:\n    * 白色书桌\n    * 单显示器，显示着柔和的蓝色壁纸（没有可读的文字）\n    * 机械键盘，白色键帽，放在蓝色桌垫上\n    * 鼠标，放在小号蓝色鼠标垫上\n    * PC主机在右侧，带有蓝色机箱灯效\n    * PC主机上或附近有三个动漫手办\n    * 墙上贴着一张佛塔海报\n    * 猫形台灯，带有蓝色点缀\n    * 一杯透明的玻璃水杯\n    * 窗边（镜头左侧）有一株高大的绿叶植物\n* **颜色替换**: 将所有原先的粉色元素（衣物和房间）替换为蓝色（婴儿蓝 -> 天空蓝/长春花蓝）。\n\n---\n\n### **灯光**\n* **光源**: 来自镜头左侧大窗户的日光，透过薄纱窗帘\n* **光线质感**: 柔和的漫射光\n* **白平衡 (K)**: 5200\n\n---\n\n### **相机**\n* **模式**: 智能手机后置摄像头通过镜子拍摄（无肖像/虚化模式）\n* **等效焦距 (mm)**: 26\n* **距离 (米)**:\n    * 主体到镜子: 0.6\n    * 相机到镜子: 0.5\n* **曝光**:\n    * 光圈 (f): 1.8\n    * 感光度 (ISO): 100\n    * 快门速度 (秒): 0.01\n    * 曝光补偿 (EV): -0.3\n* **对焦**: 对焦于镜中影像的躯干和短裤\n* **景深**: 自然的智能手机景深（深景深）；背景清晰可辨，无人为模糊\n* **构图**:\n    * **宽高比**: 1:1\n    * **裁剪**: 从头顶到大腿中部；画面包含书桌、显示器、PC主机和植物\n    * **角度**: 从镜子的视角轻微俯拍\n    * **构图备注**: 保持主体居中；为避免广角边缘拉伸，可以站远一些再进行方形裁剪\n\n---\n\n### **负面提示词**\n* 任何地方出现粉色/品红色\n* 美颜滤镜/磨皮皮肤；没有毛孔的外观\n* 夸张或扭曲的人体结构\n* NSFW，透视面料，走光\n* 商标，品牌名，可读的用户界面文本\n* 虚假的人像模式模糊，CGI/插画感",
    "translatedPromptText": "### 场景\n宅男风格电脑角里的镜面自拍，蓝色调。\n\n### 主体\n* 性别表达：女性\n* 年龄：25 岁左右\n* 种族：东亚裔\n* 身材：苗条，腰部线条分明；身体比例自然\n* 肤色：浅中性色调\n* 发型：\n    * 长度：及腰长发\n    * 样式：直发，发梢微卷\n    * 颜色：中棕色\n* 姿势：\n    * 站姿：略呈对立式平衡站姿\n    * 右手：手持智能手机置于脸前（身份隐藏）\n    * 左臂：自然下垂于身体两侧\n    * 躯干：身体略微后倾；腰部和腹部露出\n* 服装：\n    * 上衣：浅蓝色短款针织开衫，上面两颗纽扣扣上；隐约可见一件蓝色法式文胸\n    * 下装：牛仔超短裤，臀部两侧各有一个蓝色缎带蝴蝶结\n    * 袜子：蓝白条纹过膝袜\n    * 配饰：一个蓝色可爱吉祥物手机壳\n\n### 环境\n* 描述：通过壁挂镜看到的卧室电脑角\n* 家具：\n    * 白色书桌\n    * 单显示器显示柔和的蓝色壁纸（无可读文本）\n    * 机械键盘，白色键帽，置于蓝色桌垫上\n    * 鼠标置于一个小型蓝色鼠标垫上\n    * 右侧的电脑主机，带有蓝色机箱灯\n    * 电脑主机上或附近有三个动漫手办\n    * 墙上有一张宝塔海报\n    * 猫形台灯，带蓝色点缀\n    * 一杯透明玻璃水\n    * 窗边有一株高大的绿色阔叶植物（画面左侧）\n* 颜色替换：将所有原为粉色的元素（衣服和房间装饰）替换为蓝色调（从婴儿蓝到天蓝色/长春花蓝）。\n\n### 灯光\n* 光源：来自相机左侧大窗户的日光，透过薄纱窗帘\n* 光线质量：柔和、漫射光\n* 白平衡 (K)：5200\n\n### 相机\n* 模式：智能手机后置摄像头通过镜子拍摄（无人像/散景模式）\n* 等效焦距 (mm)：26\n* 距离 (m)：\n    * 主体到镜子：0.6\n    * 相机到镜子：0.5\n* 曝光：\n    * 光圈 (f)：1.8\n    * ISO：100\n    * 快门速度 (s)：0.01\n    * 曝光补偿 (EV)：-0.3\n* 对焦：对焦于镜面图像中的躯干和短裤\n* 景深：智能手机自然的深景深；背景清晰可见，无人工模糊\n* 构图：\n    * 宽高比：1:1\n    * 裁剪：从头顶到大腿中部；画面中包含书桌、显示器、电脑主机和植物\n    * 角度：从镜子的视角看，略微高角度\n    * 构图说明：主体居中；为避免广角边缘畸变，让她站得稍远一些，之后再裁剪成正方形。\n\n### 负面提示\n* 任何地方出现粉色/洋红色\n* 美颜滤镜/过度平滑的皮肤；无毛孔皮肤外观\n* 夸张或扭曲的解剖结构\n* 不雅内容、透视织物、走光\n* 标志、品牌名称或可读的用户界面文本\n* 虚假的人像模式模糊、CGI/插画感"
  },
  {
    "id": "nano-banana-000009-811",
    "rank": 9,
    "youmindId": 811,
    "title": "江户时代浮世绘风格的现代场景再现",
    "description": "一个高度结构化的图像提示，用于描绘一个被重新构想为江户时代日本浮世绘木版画的现代场景，并详细指导如何处理时代错位的科技、构图、纹理和色彩。",
    "summary": "一个高度结构化的图像提示，用于描绘一个被重新构想为江户时代日本浮世绘木版画的现代场景，并详细指导如何处理时代错位的科技、构图、纹理和色彩。",
    "authorName": "VoxcatAI",
    "authorLink": "https://x.com/VoxcatAI",
    "sourceLink": "https://x.com/VoxcatAI/status/1995497350543110411",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=811",
    "publishedAt": "Dec 01, 2025",
    "featured": true,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000009-811/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一幅日本江户时代的浮世绘木版画。整体感觉是葛饰北斋和歌川广重等大师的超现实合作，通过古老的视角重新构想现代科技。\n\n**场景：** {argument name=\"modern scene\" default=\"繁忙的涩谷十字路口\"}\n\n**江户时代转换逻辑：**\n人物身着江户时代的和服，但进行着现代活动。所有科技都被转化为超现实的江户时代等效物：\n* 智能手机是发光的、精心绘制的纸质卷轴，人们正聚精会神地阅读。\n* 地铁站和火车是巨大的铰接式木制蜈蚣车厢，在人群中穿梭。\n* 摩天大楼被重新构想成无尽的、高耸入云的木制宝塔，直插戏剧性的云层。\n* 机器人和机甲则以巨大的、身披盔甲的木版傀儡形象出现。\n\n构图采用扁平透视，带有粗大、醒目的手刻墨线轮廓。背景是高度风格化的浮世绘波浪图案和戏剧性的漩涡状云朵，远处地平线上可见富士山。\n\n图像必须看起来像一幅实物版画，而非数字绘画。\n* 纹理：整个作品中都有清晰可见的木纹纹理和粗糙的纸纤维。\n* 印刷缺陷：颜料渗色明显。模拟手工压制版画，带有轻微的颜色错位，以增加真实感。\n* 色彩调色板：严格限于传统的矿物颜料，主要使用普鲁士蓝、朱红色和柔和的赭黄色。\n* 光照：柔和、平坦、无阴影的光照，没有数字渐变。\n\n宽高比为 3:4 的竖向海报。包含描述场景的竖排日文书法，并在一个角落有一个传统的红色艺术家印章。",
    "rawPromptText": "A Japanese Edo-period Ukiyo-e woodblock print (浮世絵 木版画). The overall feeling is a surreal collaboration between masters like Hokusai and Hiroshige, reimagining modern technology through an ancient lens.\n\n**The Scene:** {argument name=\"现代场景\" default=\"繁忙的涩谷十字路口\"}\n\n**Edo Transformation Logic:**\nCharacters wear Edo-era kimono but perform modern actions. All technology is transformed into surreal Edo equivalents:\n* **Smartphones** are glowing, illustrated paper scrolls being read intently.\n* **Metro stations/Trains** are giant articulated wooden centipede carriages shuffling through crowds.\n* **Skyscrapers** are reimagined as endless, towering wooden pagodas reaching into dramatic clouds.\n* **Robots/Mecha** appear as giant, armored woodblock golems.\n\nThe composition uses a flattened perspective with large, bold, hand-carved ink outlines (太い墨線). The background features heavily stylized Ukiyo-e wave patterns and dramatic, swirling clouds, with a distant Mt. Fuji visible on the horizon.\n\nThe image must look like a physical print, not a digital painting.\n* **Texture:** Strong visible wood grain texture (木目) and rough paper fibers throughout the piece.\n* **Printing Imperfections:** Pigment bleeding is evident. Crucially, simulate hand-pressed plates with slight **color misalignment (版ズレ)** for authenticity.\n* **Color Palette:** Strictly limited to traditional mineral pigments. Dominant use of Prussian blue (浮世絵ブルー), vermilion red, and muted yellow ochre.\n* **Lighting:** Soft, flat, shadow-free lighting with no digital gradients.\n\n* **Aspect Ratio:** 3:4 vertical poster.\n* **Extras:** Include vertical Japanese calligraphy describing the scene and a traditional red artist seal stamp (落款) in a corner.",
    "translatedPromptText": "一幅日本江户时代的浮世绘木版画。整体感觉是葛饰北斋和歌川广重等大师的超现实合作，通过古老的视角重新构想现代科技。\n\n**场景：** {argument name=\"modern scene\" default=\"繁忙的涩谷十字路口\"}\n\n**江户时代转换逻辑：**\n人物身着江户时代的和服，但进行着现代活动。所有科技都被转化为超现实的江户时代等效物：\n* 智能手机是发光的、精心绘制的纸质卷轴，人们正聚精会神地阅读。\n* 地铁站和火车是巨大的铰接式木制蜈蚣车厢，在人群中穿梭。\n* 摩天大楼被重新构想成无尽的、高耸入云的木制宝塔，直插戏剧性的云层。\n* 机器人和机甲则以巨大的、身披盔甲的木版傀儡形象出现。\n\n构图采用扁平透视，带有粗大、醒目的手刻墨线轮廓。背景是高度风格化的浮世绘波浪图案和戏剧性的漩涡状云朵，远处地平线上可见富士山。\n\n图像必须看起来像一幅实物版画，而非数字绘画。\n* 纹理：整个作品中都有清晰可见的木纹纹理和粗糙的纸纤维。\n* 印刷缺陷：颜料渗色明显。模拟手工压制版画，带有轻微的颜色错位，以增加真实感。\n* 色彩调色板：严格限于传统的矿物颜料，主要使用普鲁士蓝、朱红色和柔和的赭黄色。\n* 光照：柔和、平坦、无阴影的光照，没有数字渐变。\n\n宽高比为 3:4 的竖向海报。包含描述场景的竖排日文书法，并在一个角落有一个传统的红色艺术家印章。"
  },
  {
    "id": "nano-banana-000010-532",
    "rank": 10,
    "youmindId": 532,
    "title": "火车广告风格的书籍广告图片",
    "description": "一个详细的日文提示，用于生成一个 16:9 的商业书籍风格广告，其中包含特定书籍图片和日文文案要点。",
    "summary": "一个详细的日文提示，用于生成一个 16:9 的商业书籍风格广告，其中包含特定书籍图片和日文文案要点。",
    "authorName": "KAWAI",
    "authorLink": "https://x.com/kawai_design",
    "sourceLink": "https://x.com/kawai_design/status/1992142466255114727",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=532",
    "publishedAt": "Nov 22, 2025",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000010-532/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "请生成一张广告图片。\n\n==== 广告规格 ===\n- 宽高比：16:9（横向）\n- 广告产品：第一张附件图片中的书籍\n- 主要吸睛点：将第一张附件图片中的书籍以三维方式呈现\n- 语言：日语\n- 风格：商业书籍广告\n\n# 需包含的文字：\n- 前导文案：【发售约一周后决定加印】\n\n书籍《{argument name=\"book_title_en\" default=\"Designing from Zero with AI\"}》现正热销中。\n\n亚马逊畅销书排行榜\n商业设计类销量排名第一（截至 10/15）\nhttps://t.co/QxbYpfFVj6",
    "rawPromptText": "広告画像を生成してください\n\n==== 広告の仕様 ===\n- アスペクト比: 16:9（横長）\n- 広告したい商品: 添付画像1枚目の本\n- アイキャッチ: 添付画像1枚目の本を立体的に配置\n- 使用言語: 日本語\n- テイスト: ビジネス書の広告\n\n# 掲載文字:\n- プリデッドコピー: | 【 発売1週間ほどで重版決定 】\n\n書籍「{argument name=\"書籍名\" default=\"AIでゼロからデザイン\"}」好評発売中\n\nAmazon 売れ筋ランキング\n商業デザイン売上 1位 を記録（10/15 調べ）\nhttps://t.co/QxbYpfFVj6",
    "translatedPromptText": "请生成一张广告图片。\n\n==== 广告规格 ===\n- 宽高比：16:9（横向）\n- 广告产品：第一张附件图片中的书籍\n- 主要吸睛点：将第一张附件图片中的书籍以三维方式呈现\n- 语言：日语\n- 风格：商业书籍广告\n\n# 需包含的文字：\n- 前导文案：【发售约一周后决定加印】\n\n书籍《{argument name=\"book_title_en\" default=\"Designing from Zero with AI\"}》现正热销中。\n\n亚马逊畅销书排行榜\n商业设计类销量排名第一（截至 10/15）\nhttps://t.co/QxbYpfFVj6"
  },
  {
    "id": "nano-banana-000011-13330",
    "rank": 11,
    "youmindId": 13330,
    "title": "深色单色插画风格提示词（含参考图）",
    "description": "一份为 Gemini Nano Banana Pro 2.0 设计的详细提示词，旨在将上传的照片转换为采用复古蚀刻和排线技术的深色单色插画，强调复杂的线条艺术、高对比度以及哥特式/中世纪雕版画美学。",
    "summary": "一份为 Gemini Nano Banana Pro 2.0 设计的详细提示词，旨在将上传的照片转换为采用复古蚀刻和排线技术的深色单色插画，强调复杂的线条艺术、高对比度以及哥特式/中世纪雕版画美学。",
    "authorName": "Ai Prompts Lab",
    "authorLink": "https://x.com/Aipromptslap",
    "sourceLink": "https://x.com/Aipromptslap/status/2041979550935216368",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13330",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 3,
    "imageCount": 3,
    "images": [
      "/nano-banana-images/000011-13330/01.jpg",
      "/nano-banana-images/000011-13330/02.jpg",
      "/nano-banana-images/000011-13330/03.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "以上传的照片作为参考，深色单色插画风格，精细的雕版线条艺术，复古蚀刻技术，高对比度蓝灰色调，手绘墨水插画，超精细毛发纹理，复杂的线条阴影，排线和刮板画风格，戏剧性的阴影光效，古籍插画质感，写实的解剖结构与风格化线条，中世纪雕版画美学，粗犷的墨水笔触，高纹理表面，深邃阴影，细腻线条，古典版画风格，哥特式插画氛围，暗黑奇幻写实主义，精细的皱纹和胡须纹理，锐利的轮廓，柔和的冷色调，专业的木刻雕版风格，超精细，高分辨率，电影级光效，情绪化氛围。 --ar 9:16。",
    "rawPromptText": "Use the Uploaded photo as reference, Dark monochrome illustration style, detailed engraving line art, vintage etching technique, high contrast blue-gray palette, hand-drawn ink illustration, ultra detailed fur texture, intricate line shading, crosshatching and scratchboard style, dramatic shadow lighting, old book illustration look, realistic anatomy with stylized lines, medieval engraving aesthetic, rough ink strokes, highly textured surfaces, deep shadows, fine linework, classical printmaking style, gothic illustration mood, dark fantasy realism, detailed wrinkles and beard strands, sharp contours, muted cold tones, professional woodcut engraving style, ultra detailed, high resolution, cinematic lighting, moody atmosphere. --ar 9:16.",
    "translatedPromptText": "以上传的照片作为参考，深色单色插画风格，精细的雕版线条艺术，复古蚀刻技术，高对比度蓝灰色调，手绘墨水插画，超精细毛发纹理，复杂的线条阴影，排线和刮板画风格，戏剧性的阴影光效，古籍插画质感，写实的解剖结构与风格化线条，中世纪雕版画美学，粗犷的墨水笔触，高纹理表面，深邃阴影，细腻线条，古典版画风格，哥特式插画氛围，暗黑奇幻写实主义，精细的皱纹和胡须纹理，锐利的轮廓，柔和的冷色调，专业的木刻雕版风格，超精细，高分辨率，电影级光效，情绪化氛围。 --ar 9:16。"
  },
  {
    "id": "nano-banana-000012-13335",
    "rank": 12,
    "youmindId": 13335,
    "title": "Knolling 风格平铺提示词：带标签的拆解部件",
    "description": "这是一份专为 Nano Banana Pro 设计的详细提示词，旨在将任何物体（基于参考图像）转化为超写实的 8K Knolling 风格平铺图像。该提示词要求将物体拆解为 8 至 12 个带有标签的组件，并以精确的网格排列，强调技术编辑美学、完美的对齐以及真实的材质渲染。",
    "summary": "这是一份专为 Nano Banana Pro 设计的详细提示词，旨在将任何物体（基于参考图像）转化为超写实的 8K Knolling 风格平铺图像。该提示词要求将物体拆解为 8 至 12 个带有标签的组件，并以精确的网格排列，强调技术编辑美学、完美的对齐以及真实的材质渲染。",
    "authorName": "Tischeins",
    "authorLink": "https://x.com/tisch_eins",
    "sourceLink": "https://x.com/tisch_eins/status/2041962183207059670",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13335",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 2,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000012-13335/01.jpg",
      "/nano-banana-images/000012-13335/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "超写实 8K 俯视产品摄影，采用精确的 Knolling 构图，从提供的参考图像中提取物体，并将其完全拆解为 {argument name=\"number of components\" default=\"8 到 12\"} 个核心组件，以 90 度垂直俯视视角呈现。每个部件在极简哑光灰或原木色桌面上以精确间距进行规整的网格或平衡的放射状布局，完美对齐，无重叠，无无关道具。采用柔和的漫射多光源设置，带有轻微且受控的阴影，色彩中性真实，边缘极其锐利。高度真实的材质渲染，包括拉丝金属、模塑塑料、橡胶握把、裸露的电路板、螺丝及小型五金件。每个组件均由细白矩形框勾勒，并配有简洁的英文无衬线字体标签，标签置于部件旁且不遮挡主体。注释清晰、易读、低调，呈现出技术编辑美学，无水印，无 Logo，画面整洁。",
    "rawPromptText": "Ultra-realistic 8K overhead product photograph in precise knolling composition, straight top-down 90-degree view of the object from the provided reference image completely taken apart into {argument name=\"number of components\" default=\"8 to 12\"} essential components, each piece arranged with exact spacing in a disciplined grid or balanced radial layout on a minimalist matte gray or natural wood tabletop, flawless alignment, zero overlap, no unrelated props, soft diffused multi-light setup with gentle controlled shadows, neutral true-to-life color, edge-to-edge sharpness, highly authentic material rendering including brushed metal, molded plastic, rubberized grips, exposed circuit boards, screws and small hardware, every component outlined with a thin white rectangular frame and paired with a concise English sans-serif label placed adjacent to the part without obscuring it, annotations crisp, readable, understated, technical editorial aesthetic, no watermark, no logo, no clutter",
    "translatedPromptText": "超写实 8K 俯视产品摄影，采用精确的 Knolling 构图，从提供的参考图像中提取物体，并将其完全拆解为 {argument name=\"number of components\" default=\"8 到 12\"} 个核心组件，以 90 度垂直俯视视角呈现。每个部件在极简哑光灰或原木色桌面上以精确间距进行规整的网格或平衡的放射状布局，完美对齐，无重叠，无无关道具。采用柔和的漫射多光源设置，带有轻微且受控的阴影，色彩中性真实，边缘极其锐利。高度真实的材质渲染，包括拉丝金属、模塑塑料、橡胶握把、裸露的电路板、螺丝及小型五金件。每个组件均由细白矩形框勾勒，并配有简洁的英文无衬线字体标签，标签置于部件旁且不遮挡主体。注释清晰、易读、低调，呈现出技术编辑美学，无水印，无 Logo，画面整洁。"
  },
  {
    "id": "nano-banana-000013-13329",
    "rank": 13,
    "youmindId": 13329,
    "title": "带有机械龙元素的粉笔画风格奇幻 Logo",
    "description": "这是为 Nano Banana Pro 设计的提示词，旨在深色纹理项目上生成粉笔画风格的奇幻 Logo，特色在于将粗体风格化文字与机械龙图案及发光电路装饰相结合，适用于 VTuber 或品牌推广。",
    "summary": "这是为 Nano Banana Pro 设计的提示词，旨在深色纹理项目上生成粉笔画风格的奇幻 Logo，特色在于将粗体风格化文字与机械龙图案及发光电路装饰相结合，适用于 VTuber 或品牌推广。",
    "authorName": "Shah",
    "authorLink": "https://x.com/ai_with_shah",
    "sourceLink": "https://x.com/ai_with_shah/status/2041909254257340819",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13329",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 4,
    "imageCount": 4,
    "images": [
      "/nano-banana-images/000013-13329/01.jpg",
      "/nano-banana-images/000013-13329/02.jpg",
      "/nano-banana-images/000013-13329/03.jpg",
      "/nano-banana-images/000013-13329/04.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "深色纹理项目上的粉笔画风格奇幻 Logo，粗体风格化文字与机械龙图案及发光电路装饰融为一体，富有表现力的粉笔笔触带有细腻的涂抹感和色彩层次，戏剧性的侧光在表面营造出深度感，边缘细节丰富，非常适合 VTuber 或品牌推广使用。",
    "rawPromptText": "Chalk-art style fantasy logo on a dark textured board, bold stylized text integrated with mechanical dragon motifs and glowing circuit accents, expressive chalk strokes with subtle smudges and layered colors, dramatic side lighting creating depth on the surface, versatile for VTuber or branding use with high detail on edges.",
    "translatedPromptText": "深色纹理项目上的粉笔画风格奇幻 Logo，粗体风格化文字与机械龙图案及发光电路装饰融为一体，富有表现力的粉笔笔触带有细腻的涂抹感和色彩层次，戏剧性的侧光在表面营造出深度感，边缘细节丰富，非常适合 VTuber 或品牌推广使用。"
  },
  {
    "id": "nano-banana-000014-13327",
    "rank": 14,
    "youmindId": 13327,
    "title": "金发美女与 G-Wagon 的结构化提示词",
    "description": "一份针对 Nano Banana 2 的结构化 JSON 提示词，详细描述了一位时尚的年轻金发女性站在欧洲城市街道的黑色梅赛德斯 G-Wagon 前，强调奢华生活方式、网红审美以及具有特定相机和光影设置的抓拍街拍风格。",
    "summary": "一份针对 Nano Banana 2 的结构化 JSON 提示词，详细描述了一位时尚的年轻金发女性站在欧洲城市街道的黑色梅赛德斯 G-Wagon 前，强调奢华生活方式、网红审美以及具有特定相机和光影设置的抓拍街拍风格。",
    "authorName": "Lore",
    "authorLink": "https://x.com/l_w_lorenzen",
    "sourceLink": "https://x.com/l_w_lorenzen/status/2041890544482447401",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13327",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000014-13327/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "{\n  \"prompt\": \"一位时尚的年轻金发女性，留着波浪长发，站在欧洲城市街道上，背景是一辆黑色梅赛德斯 G-Wagon。她手里拿着一杯装有吸管的绿色果汁，身穿修身白色长袖露脐上衣和宽松的浅色水洗牛仔裤。她背着一个粉色单肩包，佩戴极简金色首饰，妆容自然。背景是带有白色装饰和阳台的优雅米色联排别墅，柔和的阴天光线，奢华生活方式美学，抓拍街拍风格。\",\n  \"style\": \"照片级真实感，奢华生活方式，网红审美\",\n  \"camera\": \"iPhone 拍摄效果，50mm 镜头质感，浅景深\",\n  \"lighting\": \"自然日光，柔和阴天，漫射光\",\n  \"quality\": \"超写实，8k 分辨率，高细节\",\n  \"composition\": \"主体居中，全身照，微侧姿势，街拍视角\",\n  \"aspect_ratio\": \"9:16\"\n}",
    "rawPromptText": "{\n  \"prompt\": \"A stylish young blonde woman with long wavy hair standing on a European city street, in front of a black Mercedes G-Wagon. She is holding a green juice in a clear cup with a straw, wearing a fitted white long-sleeve crop top and loose light-wash jeans. She has a pink shoulder bag, minimal gold jewelry, and natural makeup. Background features elegant beige townhouse buildings with white trim and balconies, soft overcast lighting, luxury lifestyle aesthetic, candid street photography.\",\n  \"style\": \"photorealistic, luxury lifestyle, influencer aesthetic\",\n  \"camera\": \"iPhone photo, 50mm lens look, shallow depth of field\",\n  \"lighting\": \"natural daylight, soft overcast, diffused lighting\",\n  \"quality\": \"ultra realistic, 8k, high detail\",\n  \"composition\": \"centered subject, full body, slightly angled pose, street-level perspective\",\n  \"aspect_ratio\": \"9:16\"\n}",
    "translatedPromptText": "{\n  \"prompt\": \"一位时尚的年轻金发女性，留着波浪长发，站在欧洲城市街道上，背景是一辆黑色梅赛德斯 G-Wagon。她手里拿着一杯装有吸管的绿色果汁，身穿修身白色长袖露脐上衣和宽松的浅色水洗牛仔裤。她背着一个粉色单肩包，佩戴极简金色首饰，妆容自然。背景是带有白色装饰和阳台的优雅米色联排别墅，柔和的阴天光线，奢华生活方式美学，抓拍街拍风格。\",\n  \"style\": \"照片级真实感，奢华生活方式，网红审美\",\n  \"camera\": \"iPhone 拍摄效果，50mm 镜头质感，浅景深\",\n  \"lighting\": \"自然日光，柔和阴天，漫射光\",\n  \"quality\": \"超写实，8k 分辨率，高细节\",\n  \"composition\": \"主体居中，全身照，微侧姿势，街拍视角\",\n  \"aspect_ratio\": \"9:16\"\n}"
  },
  {
    "id": "nano-banana-000015-13334",
    "rank": 15,
    "youmindId": 13334,
    "title": "电影感城市街景：四轮摩托车与老年夫妇",
    "description": "这是一个为 Nano Banana 设计的电影感提示词，旨在生成一个城市街景：一辆黄色 Yamaha 四轮摩托车在湿润的路面上表演垂直翘头。画面中包含一名 60 岁的亚洲男性驾驶着四轮摩托车，一名 60 岁的亚洲女性悬挂在下方，两人均身着时尚街头服饰，强调低角度视角、动态畸变和超写实纹理。",
    "summary": "这是一个为 Nano Banana 设计的电影感提示词，旨在生成一个城市街景：一辆黄色 Yamaha 四轮摩托车在湿润的路面上表演垂直翘头。画面中包含一名 60 岁的亚洲男性驾驶着四轮摩托车，一名 60 岁的亚洲女性悬挂在下方，两人均身着时尚街头服饰，强调低角度视角、动态畸变和超写实纹理。",
    "authorName": "Filschics",
    "authorLink": "https://x.com/MathisYanis",
    "sourceLink": "https://x.com/MathisYanis/status/2041845437909381276",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13334",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000015-13334/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "这是一个电影感城市街景，画面中一辆黄色 Yamaha 四轮摩托车正在湿润的城市巷道中表演垂直翘头。一名 60 岁的亚洲男性自信地坐在高起的四轮摩托车上，身着精致的休闲街头服饰——剪裁考究的夹克、宽松的长裤和干净的运动鞋。他的姿态放松而从容，散发着沉稳的气场。在他下方，悬挂在四轮摩托车上的 60 岁亚洲女性个性十足，姿态从容不迫。她身穿黑色皮质机车夹克（Perfecto）、修身紫色皮裤和 Air Jordan 1 运动鞋。她的表情平静、自信且略带叛逆。环境真实且充满质感：潮湿的路面、工业建筑、柔和的色调以及阴天的自然光。采用低角度拍摄以强调力量感和垂直感，并带有动态透视畸变。电影级调色、细腻的胶片颗粒感、超写实的纹理以及浅景深效果。",
    "rawPromptText": "A cinematic urban street scene featuring a yellow Yamaha quad bike performing a vertical wheelie on a wet city alley pavement. A 60-year-old Asian man sits confidently on top of the raised quad, wearing a refined casual chic streetwear outfit — tailored jacket, relaxed trousers, and clean sneakers. His posture is relaxed yet controlled, exuding quiet authority. Below him, hanging from the quad, a 60-year-old Asian woman with strong character is positioned with effortless attitude. She wears a black leather biker jacket (perfecto), fitted purple leather pants, and Air Jordan 1 sneakers. Her expression is calm, confident, slightly rebellious. The environment is gritty and realistic: damp pavement, industrial buildings, muted tones, soft overcast daylight. Shot from a low angle to emphasize power and verticality, with dynamic perspective distortion. Cinematic color grading, subtle film grain, ultra-realistic textures, shallow depth of field.",
    "translatedPromptText": "这是一个电影感城市街景，画面中一辆黄色 Yamaha 四轮摩托车正在湿润的城市巷道中表演垂直翘头。一名 60 岁的亚洲男性自信地坐在高起的四轮摩托车上，身着精致的休闲街头服饰——剪裁考究的夹克、宽松的长裤和干净的运动鞋。他的姿态放松而从容，散发着沉稳的气场。在他下方，悬挂在四轮摩托车上的 60 岁亚洲女性个性十足，姿态从容不迫。她身穿黑色皮质机车夹克（Perfecto）、修身紫色皮裤和 Air Jordan 1 运动鞋。她的表情平静、自信且略带叛逆。环境真实且充满质感：潮湿的路面、工业建筑、柔和的色调以及阴天的自然光。采用低角度拍摄以强调力量感和垂直感，并带有动态透视畸变。电影级调色、细腻的胶片颗粒感、超写实的纹理以及浅景深效果。"
  },
  {
    "id": "nano-banana-000016-13328",
    "rank": 16,
    "youmindId": 13328,
    "title": "时尚男士高定大片提示词",
    "description": "这是一份为 PixPrettyAI 上的 Nano Banana 2 编写的详细图像生成提示词，描述了一位身着全黑定制西装的时尚男士，背景为纯黑，配以金色配饰、戏剧性光影，呈现出高定时尚大片的视觉效果。",
    "summary": "这是一份为 PixPrettyAI 上的 Nano Banana 2 编写的详细图像生成提示词，描述了一位身着全黑定制西装的时尚男士，背景为纯黑，配以金色配饰、戏剧性光影，呈现出高定时尚大片的视觉效果。",
    "authorName": "Harboris",
    "authorLink": "https://x.com/harboriis",
    "sourceLink": "https://x.com/harboriis/status/2041795600715542871",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13328",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000016-13328/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一位身着利落全黑装束的时尚男士在纯黑背景前自信地摆出姿势。他穿着定制的黑色西装，黑色衬衫领口微敞，颈间佩戴着一条精致的金色项链。他戴着金色太阳镜，留着修剪整齐的胡须，散发出迷人而神秘的气质。左手腕上的奢华腕表闪烁着微光，戏剧性的灯光突显出他的面部轮廓并投下柔和的阴影，营造出大胆且极具高定时尚感的大片视觉效果。",
    "rawPromptText": "A stylish man a sleek, all-black outfit poses confidently against a pitch-black background. He wears a tailored black suit, a black shirt with the top buttons open, and a subtle gold chain around his neck, he sports golden sunglasses and a well-groomed beard, exuding charisma and mystery A luxury wristwatch glint on his left wrist, the lighting is dramatic, highlighting his facial features and casting soft shas, creating a bold, high -fashion editorial look",
    "translatedPromptText": "一位身着利落全黑装束的时尚男士在纯黑背景前自信地摆出姿势。他穿着定制的黑色西装，黑色衬衫领口微敞，颈间佩戴着一条精致的金色项链。他戴着金色太阳镜，留着修剪整齐的胡须，散发出迷人而神秘的气质。左手腕上的奢华腕表闪烁着微光，戏剧性的灯光突显出他的面部轮廓并投下柔和的阴影，营造出大胆且极具高定时尚感的大片视觉效果。"
  },
  {
    "id": "nano-banana-000017-13332",
    "rank": 17,
    "youmindId": 13332,
    "title": "元素碰撞的电影级暗黑奇幻场景",
    "description": "这是一个推荐用于 Gemini Nano Banana 的复杂多部分提示词，旨在生成一个电影级的暗黑奇幻场景：上传的角色坐在地下室中，掌心流淌出熔岩与寒冰，两者碰撞形成象征性的毁灭交汇点，并不断衍生出各种生物。",
    "summary": "这是一个推荐用于 Gemini Nano Banana 的复杂多部分提示词，旨在生成一个电影级的暗黑奇幻场景：上传的角色坐在地下室中，掌心流淌出熔岩与寒冰，两者碰撞形成象征性的毁灭交汇点，并不断衍生出各种生物。",
    "authorName": "Edizkan ⭕🦇",
    "authorLink": "https://x.com/edizkan_",
    "sourceLink": "https://x.com/edizkan_/status/2041750096199422411",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13332",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000017-13332/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一个电影级的暗黑奇幻场景，展示了上传的参考角色坐在地下室中，其身体正源源不断地诞生出对立的元素力量。形象完整性（关键）：保留上传角色的确切身份。保持精确的比例、眼型、间距、风格化特征、轮廓及材质特征。不要将其人类化。不要重新诠释解剖结构。不要修改面部结构。不要添加非预期的配饰。身份必须保持一眼可辨。核心场景：角色以忧郁、沉重的姿态坐在冰冷的毛坯地下室中央。一只手掌向下流淌着持续发光的熔岩流。另一只手掌向下流淌着持续的结晶冰霜流。两种元素倾泻在地下室地面上，形成两条流动的河流：一条熔岩河，一条冰河。它们在混凝土路面上向相反方向流动，并在场景附近交汇。元素交互：在河流交汇处，碰撞产生了强烈的物理对比：蒸汽、发光的裂纹、冰霜绽放、发黑的湿混凝土、冷却的岩石和冰冷的碎片。交汇点必须具有情感象征意义，如同两种内心状态的碰撞。生物创造故事（关键）：从掌心流出的熔岩和冰正在地面上活跃地创造生物。这些生物必须感觉像是从流动的物质本身中诞生，而不是事后放置在场景中的。有些生物仍在从流体中成形。有些已经完全成形，在坐着的角色周围徘徊。熔岩生物：发光、半熔融、带有余烬脉络、受热扭曲的轮廓。冰霜生物：半透明、结霜、结晶、边缘锋利、冷蒸汽构成的轮廓。它们的大小和种类应各不相同，涵盖各种动物和昆虫。一些熔岩和冰霜生物已经围绕在角色身边，表现出安静的忠诚或沉默的观察。角色姿态与情感：角色坐着，静止，内省，情感疲惫。头部微垂。双肩承载着无形的重压。手掌张开并向下倾斜，使熔岩和冰自然流出。姿态必须同时传达出悲伤、克制与力量感。不是胜利的施法姿态。不是动作英雄的能量。而是安静的哀愁。受控的毁灭。环境：一个阴暗的地下室内部，具有：未完工的混凝土底面、老旧墙壁、管道和裸露的结构、细微的水渍、极少的物体、深邃的负空间。地下室应感觉真实、空旷且略显荒废。元素河流成为主要的叙事手段。摄像机与视角：使用低位电影视角，略低于坐着角色的视线。镜头：24mm 或 28mm。摄像机距离足够近以产生亲密感，但视野足够宽，可以展示在地面上蔓延的河流以及围绕角色的生物。构图应略微偏离中心，不对称。利用前景深度，在镜头附近放置一两个模糊的生物或碎片。坐着的角色始终是情感锚点。景深：主要焦平面锁定在角色的面部、上半身和倾泻的双掌上。最近的生物和河流交汇点可以保持轻微的可辨识度。前景和远背景逐渐失焦。不要全画幅清晰。照明：主光：头顶一盏微弱的冷色地下室灯，昏暗且情感冰冷。环境光：整个地下室充满深蓝色的低光氛围。辅助光自然来自熔岩本身，将温暖的橙红色底光投射到角色和附近生物的部分区域。冰霜贡献了微弱的冷色反射和微妙的蓝白色边缘高光。照明必须保持方向性和电影感，具有深沉的阴影块和受控的对比度。不要使用平光。色彩分级：主色调：深蓝、冷灰、黑色阴影。点缀：熔岩的熔融橙红色，冰霜的浅青蓝色。冷暖元素必须保持清晰的分离和情感上的可读性。受控的饱和度，电影级的高光衰减，无色彩溢出。氛围：地下室薄雾。熔岩与冰交汇处升起的蒸汽。冰霜生物周围的冷蒸汽。捕捉微弱顶灯的细微空气尘埃。空气应感觉沉重而孤独。情绪：忧郁。神话感但扎根于现实。场景应感觉像是外化到物理世界中的内心冲突。角色并没有指挥这些生物。它们只是从角色无法压抑的内心深处涌现出来。负面约束：无英雄战斗姿态。无欢快的奇幻照明。无平庸的地下室渲染。无对称的中心构图。无通用的火球或魔法光环。无全身清晰度。无随机杂物。无可爱的卡通表情（除非该表情已属于角色身份）。宽高比：ar 16:9",
    "rawPromptText": "A cinematic dark fantasy scene of the uploaded reference character seated in a basement at the exact point where opposite elemental forces are born from their own body. Likeness Integrity (CRITICAL) Preserve the exact identity of the uploaded character. Maintain exact proportions, eye shape, spacing, stylization, silhouette, and material identity. Do not humanize. Do not reinterpret anatomy. Do not modify facial structure. Do not add unintended accessories. Identity must remain instantly recognizable. Core Scene The character is sitting in a melancholic, emotionally heavy pose at the center of a cold unfinished basement. From one open palm, molten lava pours downward in a continuous glowing stream. From the other open palm, freezing ice and frost pour downward in a continuous crystalline stream. Both elements spill onto the basement floor and form two separate flowing rivers: one lava river, one ice river. They travel across the concrete floor in opposite directions and meet nearby in the same scene. Elemental Interaction Where the rivers meet, the collision creates violent physical contrast: steam, glowing cracks, frost bloom, blackened wet concrete, cooling rock, and frozen shards. The meeting point must feel emotionally symbolic, like two inner states colliding. Creature Creation Story (CRITICAL) The lava and ice pouring from the palms are actively creating creatures on the floor. These creatures must feel born from the flowing material itself, not placed into the scene afterward. Some creatures are still forming out of the streams. Some are fully shaped and wandering around the seated character. Lava creatures: glowing, semi-molten, ember-veined, heat-distorted silhouettes. Ice creatures: translucent, frosted, crystalline, sharp-edged, cold-vapor silhouettes. They should vary in size and animals language, all kind of animals and insects. A few lava and ice creatures are already surrounding the character in quiet loyalty or silent observation. Character Pose & Emotion The character is seated, still, introspective, emotionally exhausted. Head slightly lowered. Shoulders carrying invisible weight. Palms open and angled downward so the lava and ice pour naturally from them. The pose must feel like grief, restraint, and power at the same time. Not a triumphant spellcasting pose. Not action-hero energy. Quiet sorrow. Controlled destruction. Environment A dark basement interior with: unfinished concrete floor, aged walls, pipes and exposed structure, subtle moisture stains, minimal objects, deep negative space. The basement should feel real, sparse, and slightly abandoned. The elemental rivers become the main environmental storytelling device. Camera & Perspective Use a low cinematic perspective, slightly below the seated character's eye line. Lens: 24mm or 28mm. The camera is close enough to feel intimate but wide enough to show the rivers spreading across the floor and the creatures surrounding the character. Composition should be slightly off-center, not symmetrical. Use foreground depth with one or two blurred creatures or fragments near the lens. The seated character remains the emotional anchor. Depth of Field Primary focal plane locked on the character's face, upper torso, and both pouring palms. Nearest creatures and the river collision point can remain slightly readable. Foreground and far background fall progressively out of focus. No full-frame sharpness. Lighting Main light: a weak cool basement lamp overhead, dim and emotionally cold. Ambient: dark blue low-light atmosphere throughout the basement. Secondary light comes naturally from the lava itself, casting warm orange-red underlight onto parts of the character and nearby creatures. Ice contributes faint cold reflections and subtle blue-white edge highlights. Lighting must stay directional and cinematic, with deep shadow mass and controlled contrast. No flat lighting. Color Grade Dominant palette: dark blue, cold grey, black shadow. Accents: molten orange-red from lava, pale cyan-blue from ice. The warm and cool elements must remain clearly separated and emotionally readable. Controlled saturation, cinematic highlight roll-off, no color flooding. Atmosphere Thin basement haze. Steam rising where lava and ice meet. Cold vapor around the ice creatures. Subtle airborne dust catching the weak overhead lamp. The air should feel heavy and lonely. Mood Melancholic. Mythic but grounded. The scene should feel like inner conflict externalized into the physical world. The character is not commanding the creatures. They are simply emerging from what the character cannot hold inside. Negative Constraints No heroic battle pose. No cheerful fantasy lighting. No flat basement rendering. No symmetrical centered composition. No generic fireballs or magic aura. No full-body sharpness. No random clutter. No cute cartoon expression unless it already belongs to the character identity. Aspect Ratio ar 16:9",
    "translatedPromptText": "一个电影级的暗黑奇幻场景，展示了上传的参考角色坐在地下室中，其身体正源源不断地诞生出对立的元素力量。形象完整性（关键）：保留上传角色的确切身份。保持精确的比例、眼型、间距、风格化特征、轮廓及材质特征。不要将其人类化。不要重新诠释解剖结构。不要修改面部结构。不要添加非预期的配饰。身份必须保持一眼可辨。核心场景：角色以忧郁、沉重的姿态坐在冰冷的毛坯地下室中央。一只手掌向下流淌着持续发光的熔岩流。另一只手掌向下流淌着持续的结晶冰霜流。两种元素倾泻在地下室地面上，形成两条流动的河流：一条熔岩河，一条冰河。它们在混凝土路面上向相反方向流动，并在场景附近交汇。元素交互：在河流交汇处，碰撞产生了强烈的物理对比：蒸汽、发光的裂纹、冰霜绽放、发黑的湿混凝土、冷却的岩石和冰冷的碎片。交汇点必须具有情感象征意义，如同两种内心状态的碰撞。生物创造故事（关键）：从掌心流出的熔岩和冰正在地面上活跃地创造生物。这些生物必须感觉像是从流动的物质本身中诞生，而不是事后放置在场景中的。有些生物仍在从流体中成形。有些已经完全成形，在坐着的角色周围徘徊。熔岩生物：发光、半熔融、带有余烬脉络、受热扭曲的轮廓。冰霜生物：半透明、结霜、结晶、边缘锋利、冷蒸汽构成的轮廓。它们的大小和种类应各不相同，涵盖各种动物和昆虫。一些熔岩和冰霜生物已经围绕在角色身边，表现出安静的忠诚或沉默的观察。角色姿态与情感：角色坐着，静止，内省，情感疲惫。头部微垂。双肩承载着无形的重压。手掌张开并向下倾斜，使熔岩和冰自然流出。姿态必须同时传达出悲伤、克制与力量感。不是胜利的施法姿态。不是动作英雄的能量。而是安静的哀愁。受控的毁灭。环境：一个阴暗的地下室内部，具有：未完工的混凝土底面、老旧墙壁、管道和裸露的结构、细微的水渍、极少的物体、深邃的负空间。地下室应感觉真实、空旷且略显荒废。元素河流成为主要的叙事手段。摄像机与视角：使用低位电影视角，略低于坐着角色的视线。镜头：24mm 或 28mm。摄像机距离足够近以产生亲密感，但视野足够宽，可以展示在地面上蔓延的河流以及围绕角色的生物。构图应略微偏离中心，不对称。利用前景深度，在镜头附近放置一两个模糊的生物或碎片。坐着的角色始终是情感锚点。景深：主要焦平面锁定在角色的面部、上半身和倾泻的双掌上。最近的生物和河流交汇点可以保持轻微的可辨识度。前景和远背景逐渐失焦。不要全画幅清晰。照明：主光：头顶一盏微弱的冷色地下室灯，昏暗且情感冰冷。环境光：整个地下室充满深蓝色的低光氛围。辅助光自然来自熔岩本身，将温暖的橙红色底光投射到角色和附近生物的部分区域。冰霜贡献了微弱的冷色反射和微妙的蓝白色边缘高光。照明必须保持方向性和电影感，具有深沉的阴影块和受控的对比度。不要使用平光。色彩分级：主色调：深蓝、冷灰、黑色阴影。点缀：熔岩的熔融橙红色，冰霜的浅青蓝色。冷暖元素必须保持清晰的分离和情感上的可读性。受控的饱和度，电影级的高光衰减，无色彩溢出。氛围：地下室薄雾。熔岩与冰交汇处升起的蒸汽。冰霜生物周围的冷蒸汽。捕捉微弱顶灯的细微空气尘埃。空气应感觉沉重而孤独。情绪：忧郁。神话感但扎根于现实。场景应感觉像是外化到物理世界中的内心冲突。角色并没有指挥这些生物。它们只是从角色无法压抑的内心深处涌现出来。负面约束：无英雄战斗姿态。无欢快的奇幻照明。无平庸的地下室渲染。无对称的中心构图。无通用的火球或魔法光环。无全身清晰度。无随机杂物。无可爱的卡通表情（除非该表情已属于角色身份）。宽高比：ar 16:9"
  },
  {
    "id": "nano-banana-000018-13331",
    "rank": 18,
    "youmindId": 13331,
    "title": "海边男士黑白肖像",
    "description": "一个用于 Nano Banana 2 的提示词，旨在生成一张美观的男士海边黑白肖像。画面包含戏剧性的柔和光影、高对比度、胶片颗粒感以及细腻的织物纹理。",
    "summary": "一个用于 Nano Banana 2 的提示词，旨在生成一张美观的男士海边黑白肖像。画面包含戏剧性的柔和光影、高对比度、胶片颗粒感以及细腻的织物纹理。",
    "authorName": "Harboris",
    "authorLink": "https://x.com/harboriis",
    "sourceLink": "https://x.com/harboriis/status/2041746207190732836",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13331",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 2,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000018-13331/01.jpg",
      "/nano-banana-images/000018-13331/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "在不改变面部特征的前提下进行肖像创作。一张美观的男士黑白肖像。他坐在海边的木椅上，神情放松，注视着镜头。他身穿一件解开扣子的白色宽松衬衫和蓝色阔腿牛仔裤，体格健壮。画面呈现戏剧性的柔和光影、高对比度及胶片颗粒感。背景为模糊的海浪与阴天。高度细节化，艺术摄影风格。",
    "rawPromptText": "A portrait without changing facial features. An aesthetically pleasing black and white portrait of a man. He sits on a wooden chair by the seashore, looking at the camera, relaxed. He is wearing an unbuttoned white loose shirt and loose blue baggy jeans. He has an athletic build. Dramatic soft lighting, high contrast, and film grain. The background features blurred sea waves and overcast weather. Highly detailed, art photography style.",
    "translatedPromptText": "在不改变面部特征的前提下进行肖像创作。一张美观的男士黑白肖像。他坐在海边的木椅上，神情放松，注视着镜头。他身穿一件解开扣子的白色宽松衬衫和蓝色阔腿牛仔裤，体格健壮。画面呈现戏剧性的柔和光影、高对比度及胶片颗粒感。背景为模糊的海浪与阴天。高度细节化，艺术摄影风格。"
  },
  {
    "id": "nano-banana-000019-13325",
    "rank": 19,
    "youmindId": 13325,
    "title": "充满活力的韩剧宣传海报",
    "description": "用于生成一张充满活力、色彩鲜艳的韩剧宣传海报的提示词。画面包含四位年轻韩国演员，他们以欢快的姿态合影，背景为明亮的渐变色，并详细描述了他们的动作、服装及整体风格。",
    "summary": "用于生成一张充满活力、色彩鲜艳的韩剧宣传海报的提示词。画面包含四位年轻韩国演员，他们以欢快的姿态合影，背景为明亮的渐变色，并详细描述了他们的动作、服装及整体风格。",
    "authorName": "Cherry 2.O",
    "authorLink": "https://x.com/Mind_Boticni",
    "sourceLink": "https://x.com/Mind_Boticni/status/2041729292149862780",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13325",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000019-13325/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一张充满活力、色彩鲜艳的韩剧宣传海报，画面中四位年轻的韩国演员在明亮的白蓝色渐变背景下，以欢快、充满能量的姿态合影，背景上方是清澈的蓝天。\n前景中，一位留着深色长发的年轻女性身穿白色高领上衣，外搭带有红色花卉图案的白色无袖连衣裙，她张嘴大笑，右手食指直指镜头。\n在她后方左侧，一位留着红棕色长发的女性身穿紫色西装外套，面带微笑，右手食指指向天空。\n后方中央，一位留着深色短发的男性身穿橙色衬衫，外搭深蓝色夹克，他面带微笑，右手握拳举向空中。\n右侧，一位留着深色短发的男性身穿浅蓝色针织衫，笑容灿烂，右手竖起大拇指。\n整体构图明亮、有趣且充满青春气息，采用干净的摄影棚灯光，高分辨率，呈现出韩剧典型的宣传海报风格。",
    "rawPromptText": "A vibrant, colorful K-drama promotional poster featuring four young Korean actors in a cheerful, energetic group pose against a bright white and light blue gradient background with a clear blue sky at the top.\nIn the foreground, a young woman with long dark hair, wearing a white turtleneck top under a white sleeveless dress with red floral patterns, is smiling widely with her mouth open and pointing directly at the camera with her right index finger.\nBehind her and to the left, a woman with long reddish-brown hair in a purple blazer is smiling and pointing upward with her right index finger.\nIn the center back, a man with dark hair wearing a dark blue jacket over an orange shirt is smiling with his right fist raised in the air.\nOn the right, a man with short dark hair in a light blue knit sweater is smiling brightly and making a thumbs-up gesture with his right hand.\nThe overall composition is bright, fun, and youthful with clean studio lighting, high resolution, and a promotional poster style typical of Korean television dramas.",
    "translatedPromptText": "一张充满活力、色彩鲜艳的韩剧宣传海报，画面中四位年轻的韩国演员在明亮的白蓝色渐变背景下，以欢快、充满能量的姿态合影，背景上方是清澈的蓝天。\n前景中，一位留着深色长发的年轻女性身穿白色高领上衣，外搭带有红色花卉图案的白色无袖连衣裙，她张嘴大笑，右手食指直指镜头。\n在她后方左侧，一位留着红棕色长发的女性身穿紫色西装外套，面带微笑，右手食指指向天空。\n后方中央，一位留着深色短发的男性身穿橙色衬衫，外搭深蓝色夹克，他面带微笑，右手握拳举向空中。\n右侧，一位留着深色短发的男性身穿浅蓝色针织衫，笑容灿烂，右手竖起大拇指。\n整体构图明亮、有趣且充满青春气息，采用干净的摄影棚灯光，高分辨率，呈现出韩剧典型的宣传海报风格。"
  },
  {
    "id": "nano-banana-000020-13326",
    "rank": 20,
    "youmindId": 13326,
    "title": "花园中女性的写实肖像",
    "description": "一份详细的提示词，用于生成一张电影感照片级写实肖像：一位年轻女性坐在细雨蒙蒙的绿色花园中，手持芋头叶作为雨伞。重点刻画其外貌、服饰、妆容细节以及梦幻般的氛围。",
    "summary": "一份详细的提示词，用于生成一张电影感照片级写实肖像：一位年轻女性坐在细雨蒙蒙的绿色花园中，手持芋头叶作为雨伞。重点刻画其外貌、服饰、妆容细节以及梦幻般的氛围。",
    "authorName": "Zara",
    "authorLink": "https://x.com/ZaraIrahh",
    "sourceLink": "https://x.com/ZaraIrahh/status/2041723240431911305",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13326",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000020-13326/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一位年轻女性坐在绿意盎然的花园中央，周围点缀着白色和粉色的小花，细雨正轻轻落下。她留着一头波浪状的深棕色长发。她手持一片柔软的绿色大芋头叶作为雨伞，叶片表面清晰可见雨滴。她看向镜头，温柔地微笑，双眸闪烁着光芒。\n\n她身穿一件象牙白长裙（轻盈飘逸的材质），带有彼得潘领细节，颈部系着一个小蝴蝶结。她的妆容是柔和的抖音风格（透亮的肌肤、干净的哑光底妆、柔和晕染的粉色腮红、鼻梁和颧骨处细微的高光、纤细的眼线、柔粉色眼影、自然的眉形和长长的漫画睫毛、水润的粉色嘴唇）。\n\n背景是一片绿草地，采用浅景深效果，野花略显模糊，呈现出细雨缓缓飘落的梦幻氛围。柔和的自然光，阴天带来的微弱逆光。整体呈现出清新、干净且具有电影质感的照片级写实效果。",
    "rawPromptText": "Realistic portrait of a young woman sitting in the middle of a green garden filled with small white and pink flowers as a light rain falls. She has long wavy dark brown hair. She held a soft green large taro leaf as umbrella, with raindrops clearly visible on its surface. She look at camera, smile softly and sparkling eyes. \n\nShe wore a long ivory white dress (light and flowy material) with a Peter Pan collar detail and a small bow at the neck. Her makeup is soft douyin style makeup (glowing skin, clean matte foundation, soft blended pink blush, subtle highlights on the nose and cheekbones, thin eyeliner , soft pink eyeshadow, natural brow and long manhwa lashes, glossy pink lips. \n\nThe background is a stretch of green grass with a shallow depth of field, slightly blurred wildflowers, and the effect of slowly falling rain with dreamy vibe. Soft natural lighting, little backlight from the cloudy sky. fresh, clean, and cinematic photorealistic feel.",
    "translatedPromptText": "一位年轻女性坐在绿意盎然的花园中央，周围点缀着白色和粉色的小花，细雨正轻轻落下。她留着一头波浪状的深棕色长发。她手持一片柔软的绿色大芋头叶作为雨伞，叶片表面清晰可见雨滴。她看向镜头，温柔地微笑，双眸闪烁着光芒。\n\n她身穿一件象牙白长裙（轻盈飘逸的材质），带有彼得潘领细节，颈部系着一个小蝴蝶结。她的妆容是柔和的抖音风格（透亮的肌肤、干净的哑光底妆、柔和晕染的粉色腮红、鼻梁和颧骨处细微的高光、纤细的眼线、柔粉色眼影、自然的眉形和长长的漫画睫毛、水润的粉色嘴唇）。\n\n背景是一片绿草地，采用浅景深效果，野花略显模糊，呈现出细雨缓缓飘落的梦幻氛围。柔和的自然光，阴天带来的微弱逆光。整体呈现出清新、干净且具有电影质感的照片级写实效果。"
  },
  {
    "id": "nano-banana-000022-13324",
    "rank": 22,
    "youmindId": 13324,
    "title": "肖像大师对象：线绳电话证件照",
    "description": "一个用于 Nano Banana 2 的提示词，旨在创作一张“肖像大师对象”图像，展示两张由手指捏住的护照尺寸照片，照片中的人物通过线绳电话的错觉连接在一起，需要提供面部参考图。",
    "summary": "一个用于 Nano Banana 2 的提示词，旨在创作一张“肖像大师对象”图像，展示两张由手指捏住的护照尺寸照片，照片中的人物通过线绳电话的错觉连接在一起，需要提供面部参考图。",
    "authorName": "simeon-sanai",
    "authorLink": "https://x.com/Naiknelofar788",
    "sourceLink": "https://x.com/Naiknelofar788/status/2041695940797690203",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13324",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000022-13324/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "创建一个肖像大师对象：两张由人的拇指和食指并排捏住的护照尺寸照片。\n**证件照背景：** 使用纯蓝色背景（这是印度尼西亚结婚证件照在特定出生年份奇偶数情况下的标准官方底色）。\n**服装：** 照片中的两位主体均穿着正式且整洁的白色翻领衬衫。\n**男性主体（左侧照片）：** 使其面部和发型与提供的参考图 100% 相似。\n他摆出对着白色纸杯说话的姿势，表情开朗大笑。\n**女性主体（右侧照片）：** 使其面部和发型与提供的参考图 100% 相似。\n她摆出将白色纸杯贴在耳边倾听的姿势。表情俏皮，露齿大笑并微微吐舌。\n**互动道具：** 有一根白色线绳从男性的纸杯下方引出，连接到女性的纸杯上。由于两张照片并排放置，这一道具营造出连接两张照片的“线绳电话”错觉。",
    "rawPromptText": "Create a Portrait Master Object: Two passport-sized photo prints held side-by-side by a person's thumb and index finger.\n**Passport Photo Background:** Use a solid blue background (the standard official passport photo color for Indonesian marriage books for certain even/odd birth years).\n**Clothing:** Both subjects in the photo wear formal and neat white collared shirts.\n**Male Subject (Left Photo):** Make his face and hair 100% similar to the given reference.\nHe poses as if talking into a white paper cup, with a cheerful laughing expression.\n**Female Subject (Right Photo):** Make her face and hair 100% similar to the given reference.\nShe poses as if holding a white paper cup to her ear, listening. Her expression is funny with a wide smile and a slightly stuck-out tongue.\n**Interactive Prop:** There is a white string coming out from under the male's paper cup and connecting to the female's paper cup. Because the two photos are placed next to each other, this prop creates the illusion of a \"string phone\" connecting the two photos.",
    "translatedPromptText": "创建一个肖像大师对象：两张由人的拇指和食指并排捏住的护照尺寸照片。\n**证件照背景：** 使用纯蓝色背景（这是印度尼西亚结婚证件照在特定出生年份奇偶数情况下的标准官方底色）。\n**服装：** 照片中的两位主体均穿着正式且整洁的白色翻领衬衫。\n**男性主体（左侧照片）：** 使其面部和发型与提供的参考图 100% 相似。\n他摆出对着白色纸杯说话的姿势，表情开朗大笑。\n**女性主体（右侧照片）：** 使其面部和发型与提供的参考图 100% 相似。\n她摆出将白色纸杯贴在耳边倾听的姿势。表情俏皮，露齿大笑并微微吐舌。\n**互动道具：** 有一根白色线绳从男性的纸杯下方引出，连接到女性的纸杯上。由于两张照片并排放置，这一道具营造出连接两张照片的“线绳电话”错觉。"
  },
  {
    "id": "nano-banana-000023-13333",
    "rank": 23,
    "youmindId": 13333,
    "title": "健身房女性摆拍结构化提示词",
    "description": "这是一份用于 Google Nano Banana 2 的结构化 JSON 提示词，描述了一位在光线昏暗的健身房中，身穿棕色运动连体衣并佩戴棒球帽，侧身坐在健身长椅上微笑的雀斑年轻女性。该提示词指定了照片级真实风格、电影级光效以及浅景深效果。",
    "summary": "这是一份用于 Google Nano Banana 2 的结构化 JSON 提示词，描述了一位在光线昏暗的健身房中，身穿棕色运动连体衣并佩戴棒球帽，侧身坐在健身长椅上微笑的雀斑年轻女性。该提示词指定了照片级真实风格、电影级光效以及浅景深效果。",
    "authorName": "Sadie 🥀",
    "authorLink": "https://x.com/NameIsSudee",
    "sourceLink": "https://x.com/NameIsSudee/status/2041686784111997059",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13333",
    "publishedAt": "Apr 08, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000023-13333/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "{\"A smiling young woman with fair skin and freckles posing in a gym. She is sitting sideways on a workout bench, leaning back with one arm raised behind her head. She wears a fitted brown athletic bodysuit with thin straps and a brown baseball cap with the word '{argument name=\"cap text\" default=\"SADIE\"}' on it. Her expression is relaxed and cheerful, eyes slightly closed. The background shows a dimly lit gym environment with blurred workout equipment. Soft lighting highlights her skin and creates a cinematic, shallow depth-of-field effect.\", \"style\": \"照片级真实感，电影级光效，浅景深\", \"camera\": \"人像拍摄，中景特写，微倾斜角度\", \"environment\": \"现代室内健身房，背景虚化\", \"mood\": \"放松，自信，温暖\"}",
    "rawPromptText": "{\"A smiling young woman with fair skin and freckles posing in a gym. She is sitting sideways on a workout bench, leaning back with one arm raised behind her head. She wears a fitted brown athletic bodysuit with thin straps and a brown baseball cap with the word '{argument name=\"cap text\" default=\"SADIE\"}' on it. Her expression is relaxed and cheerful, eyes slightly closed. The background shows a dimly lit gym environment with blurred workout equipment. Soft lighting highlights her skin and creates a cinematic, shallow depth-of-field effect.\", \"style\": \"photorealistic, cinematic lighting, shallow depth of field\", \"camera\": \"portrait shot, medium close-up, slight angle\", \"environment\": \"modern indoor gym, blurred background\", \"mood\": \"relaxed, confident, warm\"}",
    "translatedPromptText": "{\"A smiling young woman with fair skin and freckles posing in a gym. She is sitting sideways on a workout bench, leaning back with one arm raised behind her head. She wears a fitted brown athletic bodysuit with thin straps and a brown baseball cap with the word '{argument name=\"cap text\" default=\"SADIE\"}' on it. Her expression is relaxed and cheerful, eyes slightly closed. The background shows a dimly lit gym environment with blurred workout equipment. Soft lighting highlights her skin and creates a cinematic, shallow depth-of-field effect.\", \"style\": \"照片级真实感，电影级光效，浅景深\", \"camera\": \"人像拍摄，中景特写，微倾斜角度\", \"environment\": \"现代室内健身房，背景虚化\", \"mood\": \"放松，自信，温暖\"}"
  },
  {
    "id": "nano-banana-000024-13314",
    "rank": 24,
    "youmindId": 13314,
    "title": "使用 Nano Banana 2 进行平面设计排版提示词",
    "description": "一个用于生成大胆平面设计构图的提示词，特色在于以沉重、紧凑的无衬线字体呈现“AI FUTURE”字样，并具备戏剧性的透视感、深度和运动错觉，采用炭灰色背景上的酸性黄色。",
    "summary": "一个用于生成大胆平面设计构图的提示词，特色在于以沉重、紧凑的无衬线字体呈现“AI FUTURE”字样，并具备戏剧性的透视感、深度和运动错觉，采用炭灰色背景上的酸性黄色。",
    "authorName": "Carolina Delgado",
    "authorLink": "https://x.com/carolletta",
    "sourceLink": "https://x.com/carolletta/status/2041576775957069940",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13314",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000024-13314/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "具有戏剧性透视感的排版构图，包含短语“{argument name=\"phrase\" default=\"AI FUTURE\"}”，使用类似 Helvetica Black Condensed 或 Akzidenz-Grotesk 的沉重、紧凑的无衬线字体。文字为明亮的酸性黄色，背景为哑光炭灰色。每个字母以多个向消失点汇聚的退缩透视进行复制，重复的细白轮廓营造出深度和运动错觉，呈现出受等轴测启发但经过扭曲处理的大胆平面设计能量。",
    "rawPromptText": "Dramatic perspective typography composition with the phrase '{argument name=\"phrase\" default=\"AI FUTURE\"}' in heavy, condensed grotesque sans-serif like Helvetica Black Condensed or Akzidenz-Grotesk. Text in bright acid yellow on matte charcoal gray background. Each letter is duplicated in multiple receding perspectives converging to a vanishing point, with repeated thin white outlines creating depth and motion illusion, isometric-inspired but warped, bold graphic design energy.",
    "translatedPromptText": "具有戏剧性透视感的排版构图，包含短语“{argument name=\"phrase\" default=\"AI FUTURE\"}”，使用类似 Helvetica Black Condensed 或 Akzidenz-Grotesk 的沉重、紧凑的无衬线字体。文字为明亮的酸性黄色，背景为哑光炭灰色。每个字母以多个向消失点汇聚的退缩透视进行复制，重复的细白轮廓营造出深度和运动错觉，呈现出受等轴测启发但经过扭曲处理的大胆平面设计能量。"
  },
  {
    "id": "nano-banana-000025-13321",
    "rank": 25,
    "youmindId": 13321,
    "title": "奢华露台夜景魅力自拍",
    "description": "这是一个高度详细且结构化的提示词，用于生成一张苗条、运动型女性的魅力自拍图像（使用参考图）。提示词指定了服装（奶油色深 V 领迷你裙）、场景（夜间户外奢华露台，背景为城市天际线）、构图（高角度自拍，广角镜头畸变）以及光照（正面闪光灯/环形灯），旨在实现超写实的商业时尚摄影效果。",
    "summary": "这是一个高度详细且结构化的提示词，用于生成一张苗条、运动型女性的魅力自拍图像（使用参考图）。提示词指定了服装（奶油色深 V 领迷你裙）、场景（夜间户外奢华露台，背景为城市天际线）、构图（高角度自拍，广角镜头畸变）以及光照（正面闪光灯/环形灯），旨在实现超写实的商业时尚摄影效果。",
    "authorName": "sammy",
    "authorLink": "https://x.com/sumiturkude007",
    "sourceLink": "https://x.com/sumiturkude007/status/2041556903877398976",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13321",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000025-13321/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "{\n  \"image_description\": {\n    \"subject\": {\n      \"use_reference_image\": true,\n      \"override\": false,\n      \"physique\": {\n        \"build\": \"苗条曲线型，运动感\",\n        \"pose\": \"自拍视角，一只手臂向镜头伸展，另一只手叉腰，身体微微倾斜\"\n      }\n    },\n    \"attire\": {\n      \"outfit\": \"修身奶油色/米白色迷你裙\",\n      \"neckline\": \"极深 V 领\",\n      \"sleeves\": \"长袖，肩部略带结构感/垫肩\",\n      \"accessories\": \"腰部配有宽大的银色水钻装饰腰带，佩戴大型细银圈耳环\"\n    },\n    \"setting\": {\n      \"location\": \"夜间户外奢华露台或度假村\",\n      \"foreground\": \"平滑的米色石材或混凝土走道\",\n      \"midground\": \"清晰的深绿色棕榈叶和热带植被\",\n      \"background\": \"夜间城市天际线，远处的发光摩天大楼，模糊的城市灯光，远景中桥梁或地标的剪影\"\n    },\n    \"composition_and_lighting\": {\n      \"camera_angle\": \"高角度自拍，伸展的手臂呈现广角镜头畸变\",\n      \"lighting_type\": \"正面闪光灯或环形灯，营造出“聚光灯下”的魅力效果\",\n      \"lighting_effects\": \"明亮主体与黑暗夜景之间的高对比度，城市灯光的柔和焦外成像（bokeh）\",\n      \"color_palette\": \"暖金色、奶油色和棕褐色，与深绿色和海军蓝夜空形成对比\",\n      \"aspect_ratio\": \"4:5 (竖屏)\"\n    },\n    \"technical_tags\": [\n      \"8k 分辨率\",\n      \"照片级真实感\",\n      \"高度细腻的皮肤纹理\",\n      \"商业时尚摄影\",\n      \"iPhone 15 Pro 拍摄\",\n      \"面部焦点清晰\",\n      \"魅力摄影\"\n    ]\n  }\n}",
    "rawPromptText": "{\n  \"image_description\": {\n    \"subject\": {\n      \"use_reference_image\": true,\n      \"override\": false,\n      \"physique\": {\n        \"build\": \"Slim-curvy, athletic\",\n        \"pose\": \"Selfie perspective, one arm extended toward the camera, other hand resting on hip, slight body tilt\"\n      }\n    },\n    \"attire\": {\n      \"outfit\": \"Form-fitting cream/off-white mini dress\",\n      \"neckline\": \"Extremely deep plunging V-neck\",\n      \"sleeves\": \"Long sleeves with slightly structured/padded shoulders\",\n      \"accessories\": \"Wide, silver rhinestone-embellished belt at the waist, large thin silver hoop earrings\"\n    },\n    \"setting\": {\n      \"location\": \"Outdoor luxury terrace or resort at night\",\n      \"foreground\": \"Smooth beige stone or concrete walkway\",\n      \"midground\": \"Sharp, dark green palm tree fronds and tropical foliage\",\n      \"background\": \"Nighttime city skyline, distant glowing skyscrapers, blurred urban lights, silhouette of a bridge or landmark in the far distance\"\n    },\n    \"composition_and_lighting\": {\n      \"camera_angle\": \"High-angle selfie, wide-angle lens distortion on the extended arm\",\n      \"lighting_type\": \"Frontal flash or ring light creating a 'deer-in-the-headlights' glamor effect\",\n      \"lighting_effects\": \"High contrast between the bright subject and the dark night background, soft bokeh on city lights\",\n      \"color_palette\": \"Warm golds, creams, and tans contrasted against deep greens and navy-blue night sky\",\n      \"aspect_ratio\": \"4:5 (Vertical)\"\n    },\n    \"technical_tags\": [\n      \"8k resolution\",\n      \"photorealistic\",\n      \"highly detailed skin texture\",\n      \"commercial fashion photography\",\n      \"shot on iPhone 15 Pro\",\n      \"sharp focus on face\",\n      \"glamour photography\"\n    ]\n  }\n}",
    "translatedPromptText": "{\n  \"image_description\": {\n    \"subject\": {\n      \"use_reference_image\": true,\n      \"override\": false,\n      \"physique\": {\n        \"build\": \"苗条曲线型，运动感\",\n        \"pose\": \"自拍视角，一只手臂向镜头伸展，另一只手叉腰，身体微微倾斜\"\n      }\n    },\n    \"attire\": {\n      \"outfit\": \"修身奶油色/米白色迷你裙\",\n      \"neckline\": \"极深 V 领\",\n      \"sleeves\": \"长袖，肩部略带结构感/垫肩\",\n      \"accessories\": \"腰部配有宽大的银色水钻装饰腰带，佩戴大型细银圈耳环\"\n    },\n    \"setting\": {\n      \"location\": \"夜间户外奢华露台或度假村\",\n      \"foreground\": \"平滑的米色石材或混凝土走道\",\n      \"midground\": \"清晰的深绿色棕榈叶和热带植被\",\n      \"background\": \"夜间城市天际线，远处的发光摩天大楼，模糊的城市灯光，远景中桥梁或地标的剪影\"\n    },\n    \"composition_and_lighting\": {\n      \"camera_angle\": \"高角度自拍，伸展的手臂呈现广角镜头畸变\",\n      \"lighting_type\": \"正面闪光灯或环形灯，营造出“聚光灯下”的魅力效果\",\n      \"lighting_effects\": \"明亮主体与黑暗夜景之间的高对比度，城市灯光的柔和焦外成像（bokeh）\",\n      \"color_palette\": \"暖金色、奶油色和棕褐色，与深绿色和海军蓝夜空形成对比\",\n      \"aspect_ratio\": \"4:5 (竖屏)\"\n    },\n    \"technical_tags\": [\n      \"8k 分辨率\",\n      \"照片级真实感\",\n      \"高度细腻的皮肤纹理\",\n      \"商业时尚摄影\",\n      \"iPhone 15 Pro 拍摄\",\n      \"面部焦点清晰\",\n      \"魅力摄影\"\n    ]\n  }\n}"
  },
  {
    "id": "nano-banana-000026-13317",
    "rank": 26,
    "youmindId": 13317,
    "title": "使用 Nano Banana 2 和人脸参考图生成的电影感生活化肖像提示词",
    "description": "一个用于生成电影感生活化肖像的提示词，主角为一位特定面孔（需参考图）的年轻女性，场景设定在野花草甸中，强调柔和光影、自然美感及浅景深效果。",
    "summary": "一个用于生成电影感生活化肖像的提示词，主角为一位特定面孔（需参考图）的年轻女性，场景设定在野花草甸中，强调柔和光影、自然美感及浅景深效果。",
    "authorName": "Meem",
    "authorLink": "https://x.com/mehvishs25",
    "sourceLink": "https://x.com/mehvishs25/status/2041542243698511948",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13317",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000026-13317/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "一位年轻女性的电影感生活化肖像，面部特征与参考图完全一致，她正坐在开满小白雏菊和黄色野花的广阔野花草甸中。她随意地坐在草地上，双腿放松并微微交叉，身体略微前倾，手中拿着一朵小白雏菊伸向镜头，营造出柔和的前景虚化效果。\n\n她拥有自然美感，面部轮廓柔和，带有淡淡的雀斑，笑容温暖，中等长度的姜红色 / 赤褐色波浪卷发在微风中自然飘动。她身穿一件柔和的淡绿色针织毛衣，上面有精致的刺绣花卉细节，下身搭配米色休闲裤。\n\n环境是明媚的春日乡村草甸，天空云层富有层次感。柔和的自然日光，暖色调，微风拂过草地和花朵。视角略低且近距离，浅景深聚焦于她的面部，前景的花朵略微失焦。\n\n照片级真实感，电影级构图，50mm 镜头，浅景深，自然色彩分级，超真实皮肤质感，柔和光影，时尚杂志摄影，高细节，8k",
    "rawPromptText": "Cinematic lifestyle portrait of a young woman with the exact same face as the reference image, sitting in a wide open wildflower meadow filled with small white daisies and yellow flowers. She is sitting casually on the grass with her legs relaxed and slightly crossed, leaning slightly forward while holding a small white daisy toward the camera with her hand, creating a soft foreground blur.\n\nShe has natural beauty, soft facial features, light freckles, warm smile, and medium-length wavy ginger / auburn hair flowing naturally in the breeze. She is wearing a soft pastel green knitted sweater with delicate embroidered floral details and beige casual trousers.\n\nThe environment is a bright spring countryside meadow under a dramatic cloudy sky. Soft natural daylight, warm tones, gentle wind moving the grass and flowers. The perspective is slightly low and close, with shallow depth of field focusing on her face while the flower in the foreground is slightly out of focus.\n\nphotorealistic, cinematic composition, 50mm lens, shallow depth of field, natural color grading, ultra realistic skin texture, soft lighting, fashion editorial photography, high detail, 8k",
    "translatedPromptText": "一位年轻女性的电影感生活化肖像，面部特征与参考图完全一致，她正坐在开满小白雏菊和黄色野花的广阔野花草甸中。她随意地坐在草地上，双腿放松并微微交叉，身体略微前倾，手中拿着一朵小白雏菊伸向镜头，营造出柔和的前景虚化效果。\n\n她拥有自然美感，面部轮廓柔和，带有淡淡的雀斑，笑容温暖，中等长度的姜红色 / 赤褐色波浪卷发在微风中自然飘动。她身穿一件柔和的淡绿色针织毛衣，上面有精致的刺绣花卉细节，下身搭配米色休闲裤。\n\n环境是明媚的春日乡村草甸，天空云层富有层次感。柔和的自然日光，暖色调，微风拂过草地和花朵。视角略低且近距离，浅景深聚焦于她的面部，前景的花朵略微失焦。\n\n照片级真实感，电影级构图，50mm 镜头，浅景深，自然色彩分级，超真实皮肤质感，柔和光影，时尚杂志摄影，高细节，8k"
  },
  {
    "id": "nano-banana-000027-13316",
    "rank": 27,
    "youmindId": 13316,
    "title": "使用 Nano Banana 2 和人脸参考图生成的电影感肖像提示词",
    "description": "这是一个为 Nano Banana 2 设计的电影感低角度肖像提示词，需要上传人脸参考图以保持身份一致性。场景描绘了一位男性主体倚靠在栏杆上，背景为深青色天空，并采用了青橙色调的模拟胶片色彩分级。",
    "summary": "这是一个为 Nano Banana 2 设计的电影感低角度肖像提示词，需要上传人脸参考图以保持身份一致性。场景描绘了一位男性主体倚靠在栏杆上，背景为深青色天空，并采用了青橙色调的模拟胶片色彩分级。",
    "authorName": "K",
    "authorLink": "https://x.com/ChillaiKalan__",
    "sourceLink": "https://x.com/ChillaiKalan__/status/2041524809046372724",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13316",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000027-13316/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "这是一张使用 50mm 镜头拍摄的电影感低角度肖像，以仰视视角拍摄男性主体，并使用上传的人脸作为参考。他随意地倚靠在风化的混凝土和金属栏杆上，双肘支撑。主体留着短深色头发，带有微妙的阳光亲吻感高光和自然的轻盈质感，发型略显凌乱。他穿着一件超大廓形、质感丰富的米色长袖圆领卫衣，呈现出宽松自然的垂坠感。\n他向右上方凝视，表情平静而内省，传达出一种沉静的自信与深思。\n柔和、温暖的自然光照亮了整个场景，在下颌线投下柔和的阴影，并通过逼真的皮肤次表面散射强调了面部结构。右侧结构元素带来的强烈前景虚化效果增加了画面的深度与构图感。\n背景是广阔、纯净的深青色天空，营造出电影级的青橙色调模拟胶片色彩分级，并带有细腻的胶片颗粒感和自然的对比度。",
    "rawPromptText": "A cinematic low-angle portrait shot on a 50mm lens, looking upward at a male subject using the uploaded face as reference. He leans casually against a weathered concrete and metal railing, resting both elbows. The subject has short dark hair with subtle sun-kissed highlights and light natural texture, with a slightly tousled appearance. He wears an oversized, textured beige long-sleeve crewneck sweatshirt with a relaxed, loose drape.\nHe gazes upward to the right with a calm, introspective expression, conveying quiet confidence and contemplation.\nSoft, warm natural sunlight illuminates the scene, casting gentle shadows along the jawline and emphasizing facial structure with realistic skin subsurface scattering. A strong foreground bokeh from a structural element on the right adds depth and framing.\nThe background is a vast, solid deep teal-cyan sky, creating a cinematic teal-and-orange analog film color grade, with subtle film grain and natural contrast.",
    "translatedPromptText": "这是一张使用 50mm 镜头拍摄的电影感低角度肖像，以仰视视角拍摄男性主体，并使用上传的人脸作为参考。他随意地倚靠在风化的混凝土和金属栏杆上，双肘支撑。主体留着短深色头发，带有微妙的阳光亲吻感高光和自然的轻盈质感，发型略显凌乱。他穿着一件超大廓形、质感丰富的米色长袖圆领卫衣，呈现出宽松自然的垂坠感。\n他向右上方凝视，表情平静而内省，传达出一种沉静的自信与深思。\n柔和、温暖的自然光照亮了整个场景，在下颌线投下柔和的阴影，并通过逼真的皮肤次表面散射强调了面部结构。右侧结构元素带来的强烈前景虚化效果增加了画面的深度与构图感。\n背景是广阔、纯净的深青色天空，营造出电影级的青橙色调模拟胶片色彩分级，并带有细腻的胶片颗粒感和自然的对比度。"
  },
  {
    "id": "nano-banana-000028-13310",
    "rank": 28,
    "youmindId": 13310,
    "title": "Nano Banana 2 的图像编辑提示词",
    "description": "这是一个与 Nano Banana 2 配合使用的简单图像编辑提示词，用于从现有画面中移除鼓手和鼓组，同时保持图像的其他部分不变。",
    "summary": "这是一个与 Nano Banana 2 配合使用的简单图像编辑提示词，用于从现有画面中移除鼓手和鼓组，同时保持图像的其他部分不变。",
    "authorName": "TechHalla",
    "authorLink": "https://x.com/techhalla",
    "sourceLink": "https://x.com/techhalla/status/2041500202943615393",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13310",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 2,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000028-13310/01.jpg",
      "/nano-banana-images/000028-13310/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "remove the drummer and the drum kit, leave everything else exactly as is.",
    "rawPromptText": "remove the drummer and the drum kit, leave everything else exactly as is.",
    "translatedPromptText": "remove the drummer and the drum kit, leave everything else exactly as is."
  },
  {
    "id": "nano-banana-000029-13311",
    "rank": 29,
    "youmindId": 13311,
    "title": "使用 Gemini Nano Banana Pro 生成幼虎 4K 壁纸的提示词",
    "description": "一份详细的提示词，用于生成高分辨率、照片级逼真的幼虎野生动物肖像，适合作为锁屏壁纸。重点强调眼睛的清晰对焦，以及具有平滑虚化背景的浅景深效果。",
    "summary": "一份详细的提示词，用于生成高分辨率、照片级逼真的幼虎野生动物肖像，适合作为锁屏壁纸。重点强调眼睛的清晰对焦，以及具有平滑虚化背景的浅景深效果。",
    "authorName": "Ozair SK",
    "authorLink": "https://x.com/Ozayrr_irl",
    "sourceLink": "https://x.com/Ozayrr_irl/status/2041492955434045544",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13311",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 2,
    "imageCount": 2,
    "images": [
      "/nano-banana-images/000029-13311/01.jpg",
      "/nano-banana-images/000029-13311/02.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "“一张高分辨率的幼虎照片，正面视角，眼神专注而充满好奇，正从一个与背景色调一致的深绿色纹理表面上方探出头来。幼虎那双充满惊奇与纯真的棕色大眼睛是画面的焦点，吸引着观众的目光。它圆圆的耳朵竖起，捕捉着光线，突显出它专注的神情。幼虎的前爪带有清晰的肉垫和细小的爪子，对称地搁在边缘上，位于脸部两侧。它那醒目的橙金色皮毛上点缀着清晰的黑色条纹，在前额、脸颊和眼周形成了独特的图案。脸颊、耳内和胸部有柔软的白色绒毛点缀。幼虎长长的白色胡须从口鼻部向外舒展。光线柔和均匀，突显了幼虎浓密皮毛的质感、眼睛的光泽以及它探出头来的绿色表面的颗粒感。焦点精准地落在幼虎的眼睛和面部，捕捉到了皮毛、胡须和眼部结构的细腻细节。景深较浅，使浓郁的绿色背景呈现出平滑、统一的虚化效果，没有任何干扰细节，从而突显主体。风格为专业的野生动物肖像，自然而亲切，仿佛是对幼虎世界的一次瞬间窥探。构图平衡，紧凑地聚焦于幼虎的头部和爪子，填满了画面的下半部分。”",
    "rawPromptText": "\"A high-resolution photograph of a baby tiger cub, viewed head-on with an intense, curious gaze, peeking over a textured, dark green surface that matches the background. The cub's large brown eyes, full of wonder and innocence, are a prominent feature, drawing the viewer's focus. Its rounded ears are perked up, catching the light and emphasizing its attentive expression. The cub's front paws, with visible pads and small claws, rest on the ledge, positioned symmetrically on either side of its face. Its striking orange-gold fur is detailed with dark, well-defined black stripes, forming distinct patterns on its forehead, cheeks, and around its eyes. Soft, white fur accents are on its cheeks, inner ears, and chest. The cub's long white whiskers spread out prominently from its muzzle. The lighting is soft and even, highlighting the textures of the cub's dense fur, the shine in its eyes, and the pebbled texture of the green surface it is peeking over. The focus is critically sharp on the cub's eyes and face, capturing fine details in its fur, whiskers, and eye structure. The depth of field is shallow, rendering the rich green background as a smooth, uniform bokeh, free of any distracting details, to isolate the subject. The style is that of a professional wildlife portrait, with a natural yet intimate feel, as if a momentary glimpse into the cub's world. The composition is balanced and tight on the cub's head and paws, filling the lower portion of the frame.\"",
    "translatedPromptText": "“一张高分辨率的幼虎照片，正面视角，眼神专注而充满好奇，正从一个与背景色调一致的深绿色纹理表面上方探出头来。幼虎那双充满惊奇与纯真的棕色大眼睛是画面的焦点，吸引着观众的目光。它圆圆的耳朵竖起，捕捉着光线，突显出它专注的神情。幼虎的前爪带有清晰的肉垫和细小的爪子，对称地搁在边缘上，位于脸部两侧。它那醒目的橙金色皮毛上点缀着清晰的黑色条纹，在前额、脸颊和眼周形成了独特的图案。脸颊、耳内和胸部有柔软的白色绒毛点缀。幼虎长长的白色胡须从口鼻部向外舒展。光线柔和均匀，突显了幼虎浓密皮毛的质感、眼睛的光泽以及它探出头来的绿色表面的颗粒感。焦点精准地落在幼虎的眼睛和面部，捕捉到了皮毛、胡须和眼部结构的细腻细节。景深较浅，使浓郁的绿色背景呈现出平滑、统一的虚化效果，没有任何干扰细节，从而突显主体。风格为专业的野生动物肖像，自然而亲切，仿佛是对幼虎世界的一次瞬间窥探。构图平衡，紧凑地聚焦于幼虎的头部和爪子，填满了画面的下半部分。”"
  },
  {
    "id": "nano-banana-000030-13320",
    "rank": 30,
    "youmindId": 13320,
    "title": "红发女性四格时尚拼贴画",
    "description": "这是一个用于生成四格时尚拼贴画的详细提示词，展示了同一位拥有亮眼红发的年轻女性，每个象限呈现不同的发型和穿搭。风格为高定时尚杂志风，融合了复古与现代美学，采用大胆的色彩背景和柔和的漫射光，以获得超精细、高分辨率的视觉效果。",
    "summary": "这是一个用于生成四格时尚拼贴画的详细提示词，展示了同一位拥有亮眼红发的年轻女性，每个象限呈现不同的发型和穿搭。风格为高定时尚杂志风，融合了复古与现代美学，采用大胆的色彩背景和柔和的漫射光，以获得超精细、高分辨率的视觉效果。",
    "authorName": "Cherry 2.O",
    "authorLink": "https://x.com/Mind_Boticni",
    "sourceLink": "https://x.com/Mind_Boticni/status/2041480217336902122",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13320",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": false,
    "resultsCount": 1,
    "imageCount": 1,
    "images": [
      "/nano-banana-images/000030-13320/01.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "同一位亮眼红发年轻女性的四格时尚拼贴画，每个象限展示不同的发型和穿搭，影棚人像，大胆的色彩背景（{argument name=\"background colors\" default=\"芥末黄，红色，橙色\"}），复古现代美学，高定时尚杂志风格，柔和的漫射光，超精细皮肤纹理，焦点清晰。\n左上：波浪红发，佩戴透明眼镜，身穿条纹 T 恤，表情中性。\n\n右上：编织红发搭配彩色配饰，身穿透视刺绣连衣裙，侧颜，优雅姿态。\n\n左下：蓬松卷发，佩戴绿色鸭舌帽，身穿红蓝运动夹克，动态姿势，手部调整衣领。\n\n右下：松散卷红发搭配白色花朵配饰，身穿腰间打结碎花衬衫，表情柔和。\n对称网格布局，鲜艳色彩对比，电影级调色，高分辨率，时尚杂志品质，85mm 镜头，浅景深。\n风格标签（可选）：\n\n时尚摄影，编辑风，鲜艳色调，复古美学，影棚灯光，超写实，4k，构图简洁",
    "rawPromptText": "Four-panel fashion collage of the same young woman with vibrant red hair, each quadrant featuring a different hairstyle and outfit, studio portrait, bold colorful backgrounds ({argument name=\"background colors\" default=\"mustard yellow, red, orange\"}), retro-modern aesthetic, high fashion editorial style, soft diffused lighting, ultra-detailed skin texture, sharp focus.\nTop-left: wavy red hair, wearing transparent glasses and striped t-shirt, neutral expression.\n\nTop-right: braided red hair with colorful accessories, wearing sheer embroidered dress, side profile, elegant pose.\n\nBottom-left: curly voluminous hair, wearing green cap and sporty red-blue jacket, dynamic pose, hand adjusting collar.\n\nBottom-right: loose curly red hair with white flower accessory, wearing floral shirt tied at waist, soft expression.\nSymmetrical grid layout, vibrant color contrast, cinematic color grading, high-resolution, editorial magazine quality, 85mm lens, shallow depth of field.\nStyle tags (optional):\n\nfashion photography, editorial, vibrant tones, retro aesthetic, studio lighting, ultra realistic, 4k, clean composition",
    "translatedPromptText": "同一位亮眼红发年轻女性的四格时尚拼贴画，每个象限展示不同的发型和穿搭，影棚人像，大胆的色彩背景（{argument name=\"background colors\" default=\"芥末黄，红色，橙色\"}），复古现代美学，高定时尚杂志风格，柔和的漫射光，超精细皮肤纹理，焦点清晰。\n左上：波浪红发，佩戴透明眼镜，身穿条纹 T 恤，表情中性。\n\n右上：编织红发搭配彩色配饰，身穿透视刺绣连衣裙，侧颜，优雅姿态。\n\n左下：蓬松卷发，佩戴绿色鸭舌帽，身穿红蓝运动夹克，动态姿势，手部调整衣领。\n\n右下：松散卷红发搭配白色花朵配饰，身穿腰间打结碎花衬衫，表情柔和。\n对称网格布局，鲜艳色彩对比，电影级调色，高分辨率，时尚杂志品质，85mm 镜头，浅景深。\n风格标签（可选）：\n\n时尚摄影，编辑风，鲜艳色调，复古美学，影棚灯光，超写实，4k，构图简洁"
  },
  {
    "id": "nano-banana-000032-13318",
    "rank": 32,
    "youmindId": 13318,
    "title": "Nano Banana Pro 巨型产品艺术装置提示词",
    "description": "这是一份针对 Nano Banana Pro 的高精度提示词，旨在保留产品参考图的精确细节，并将其置于欧洲现代城市广场中，呈现为一座 10 米高的巨型艺术装置，采用写实纪录片摄影风格。",
    "summary": "这是一份针对 Nano Banana Pro 的高精度提示词，旨在保留产品参考图的精确细节，并将其置于欧洲现代城市广场中，呈现为一座 10 米高的巨型艺术装置，采用写实纪录片摄影风格。",
    "authorName": "Oogie",
    "authorLink": "https://x.com/oggii_0",
    "sourceLink": "https://x.com/oggii_0/status/2041461023320785077",
    "arenaLink": "https://youmind.com/model-arena/image-models?id=13318",
    "publishedAt": "Apr 07, 2026",
    "featured": false,
    "grade": "A",
    "needReferenceImages": true,
    "resultsCount": 3,
    "imageCount": 3,
    "images": [
      "/nano-banana-images/000032-13318/01.jpg",
      "/nano-banana-images/000032-13318/02.jpg",
      "/nano-banana-images/000032-13318/03.jpg"
    ],
    "promptLabel": "提示词（中文翻译）",
    "promptText": "关键要求：请务必完整保留产品原貌。不得更改其形状、颜色、比例、标签、文字、Logo、纹理或任何细节。仅调整比例及周围环境。\n\n将此产品作为一座巨型艺术装置放置在城市广场中央。产品体型巨大——高度约为 {argument name=\"size\" default=\"10 米\"}，高耸于周围行人之上。它直接放置在路面上，如同通过起重机吊装至此的品牌推广活动装置。\n\n在巨型产品底部放置行人以体现比例感——有人经过，有人驻足仰望，有人正用手机拍照。行人仅达到产品底部边缘，以此凸显其宏伟体量。\n\n城市环境：欧洲现代城市广场，背景为整洁的建筑、石板路、树木及楼宇。蓝天白云。场景呈现出真实的公共艺术装置或游击营销活动的效果。\n\n巨型产品在路面上投下与太阳方位一致的真实阴影。产品上的光影与户外阳光相匹配——来自上方的温暖自然日光，色温与周围建筑及街道保持一致。\n\n从街道视角拍摄，略微仰视巨型产品。使用 24mm 广角镜头，f/8 光圈。场景必须看起来真实可信——就像有人拍摄了一张真实巨型产品置于城市中的照片。写实街头摄影，纪录片风格。",
    "rawPromptText": "CRITICAL: Preserve the product exactly as it is. Do not alter its shape, color, proportions, label, text, logo, texture, or any detail. Only change the scale and surrounding environment.\n\nPlace this product as a GIANT art installation in the middle of a city square. The product is enormous — approximately {argument name=\"size\" default=\"10 meters\"} tall, towering over the people walking around it. It sits directly on the pavement as if it was placed there by a crane for a brand activation event.\n\nSmall people around the base of the giant product for scale — some walking past, some stopping to look up, some taking photos with their phones. The people reach only to the bottom edge of the product, showing how massive it is.\n\nCity environment: a modern European city square with clean architecture, stone pavement, trees, and buildings in the background. Blue sky with a few white clouds. The scene looks like a real public art installation or a guerrilla marketing stunt.\n\nThe giant product casts a realistic large shadow on the pavement matching the sun direction. The lighting on the product matches the outdoor sunlight — warm natural daylight from above, same color temperature as the surrounding buildings and street.\n\nShot from street level, slightly looking up at the giant product. Wide angle 24mm lens, f/8. The scene must look believably real — as if someone took a photo of an actual giant product placed in a city. Photorealistic street photography, documentary style.",
    "translatedPromptText": "关键要求：请务必完整保留产品原貌。不得更改其形状、颜色、比例、标签、文字、Logo、纹理或任何细节。仅调整比例及周围环境。\n\n将此产品作为一座巨型艺术装置放置在城市广场中央。产品体型巨大——高度约为 {argument name=\"size\" default=\"10 米\"}，高耸于周围行人之上。它直接放置在路面上，如同通过起重机吊装至此的品牌推广活动装置。\n\n在巨型产品底部放置行人以体现比例感——有人经过，有人驻足仰望，有人正用手机拍照。行人仅达到产品底部边缘，以此凸显其宏伟体量。\n\n城市环境：欧洲现代城市广场，背景为整洁的建筑、石板路、树木及楼宇。蓝天白云。场景呈现出真实的公共艺术装置或游击营销活动的效果。\n\n巨型产品在路面上投下与太阳方位一致的真实阴影。产品上的光影与户外阳光相匹配——来自上方的温暖自然日光，色温与周围建筑及街道保持一致。\n\n从街道视角拍摄，略微仰视巨型产品。使用 24mm 广角镜头，f/8 光圈。场景必须看起来真实可信——就像有人拍摄了一张真实巨型产品置于城市中的照片。写实街头摄影，纪录片风格。"
  }
];

